import { test, expect } from '@playwright/test';
test('selected plan and property answers survive navigation and reload, and WhatsApp contains complete details', async ({ page }) => {
  let submitted = false;
  await page.route('**/api/estimate', async route => {
    expect(route.request().postDataJSON()).toMatchObject({ plan: 'COHOST', type: 'apartment', bedrooms: '2', city: 'Sidi Ifni', address: '12 Rue du Port', objective: 'time', duration: 'yearplus', ready: 'month', fullName: 'Test Owner', email: 'owner@example.com', consent: true, channel: 'whatsapp' });
    submitted = true;
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ ok: true, delivery: 'whatsapp_prepared', benchmark: null }) });
  });
  await page.goto('/en');
  await page.locator('[data-plan-card=COHOST] .package-cta').click();
  const bar = page.locator('#estimate');
  await bar.locator('.estimate-next').click();
  await expect(bar.locator('#estimate-city')).toBeFocused();
  await bar.locator('#estimate-city').fill('Sidi Ifni');
  await bar.locator('#estimate-address').fill('12 Rue du Port');
  await bar.locator('.estimate-next').click();
  await expect(page).toHaveURL(/\/en\/estimate$/);
  await expect(bar.locator('#estimate-objective')).toBeVisible();
  await page.reload();
  await expect(bar.locator('#estimate-objective')).toBeVisible();
  await bar.locator('.estimate-back').click();
  await expect(bar.locator('#estimate-city')).toHaveValue('Sidi Ifni');
  await bar.locator('.estimate-next').click();
  await bar.locator('#estimate-objective').selectOption('time');
  await bar.locator('#estimate-duration').selectOption('yearplus');
  await bar.locator('#estimate-ready').selectOption('month');
  await bar.locator('.estimate-next').click();
  await bar.locator('#estimate-fullName').fill('Test Owner');
  await bar.locator('#estimate-email').fill('owner@example.com');
  await bar.locator('#estimate-phone').fill('+212600000000');
  await bar.getByRole('checkbox').check();
  await bar.getByRole('radio', { name: 'WhatsApp', exact: true }).check();
  await bar.locator('.estimate-next').click();
  await expect(bar.getByRole('heading')).toHaveText('Your WhatsApp message is ready');
  const message = new URL((await bar.locator('.estimate-whatsapp').getAttribute('href'))!).searchParams.get('text')!;
  for (const value of ['COHOST', 'Sidi Ifni', '12 Rue du Port', 'owner@example.com', '+212600000000', 'Save time', 'A year or longer', 'Within a month']) expect(message).toContain(value);
  expect(submitted).toBe(true);
});
test('email delivery errors preserve contact details for retry', async ({ page }) => {
  await page.route('**/api/estimate', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'email_unavailable' }) }));
  await page.goto('/en/estimate');
  const bar = page.locator('#estimate');
  await bar.locator('#estimate-city').fill('Rabat');
  await bar.locator('#estimate-address').fill('12 Rue du Port');
  await bar.locator('.estimate-next').click();
  await bar.locator('#estimate-objective').selectOption('revenue');
  await bar.locator('#estimate-duration').selectOption('yearplus');
  await bar.locator('#estimate-ready').selectOption('now');
  await bar.locator('.estimate-next').click();
  const email = bar.getByRole('radio', { name: 'Email', exact: true });
  test.skip(!await email.isEnabled(), 'No email provider configured in this runtime.');
  await email.check();
  await bar.locator('#estimate-fullName').fill('Test Owner');
  await bar.locator('#estimate-email').fill('owner@example.com');
  await bar.getByRole('checkbox').check();
  await bar.locator('.estimate-next').click();
  await expect(bar.getByRole('alert')).toContainText('Email is temporarily unavailable');
  await expect(bar.locator('#estimate-email')).toHaveValue('owner@example.com');
});
