import type { BlogPost } from './blog';

const dates = { published: '2026-10-09', modified: '2026-10-09' };
const offer = { label: 'Notre conciergerie à Marrakech : gestion COHOST à 20 % des réservations', href: '/fr/services/conciergerie-marrakech' };

export const marrakechNeighborhoodBlogPosts: BlogPost[] = [
  {
    ...dates, slug: 'location-courte-duree-gueliz-marrakech', category: 'Guéliz · Marrakech',
    title: 'Location courte durée à Guéliz : préparer son appartement Airbnb à Marrakech',
    seoTitle: 'Airbnb à Guéliz Marrakech : guide propriétaire',
    description: 'Appartement Airbnb à Guéliz : emplacement, équipements, accès, calendrier et budget. Les vérifications utiles avant de lancer une location courte durée.',
    intro: 'Guéliz fait partie des quartiers connus de Marrakech et possède déjà une offre d’appartements en location de vacances. Pour un propriétaire, le nom du quartier ne suffit pourtant pas à évaluer un logement. L’adresse, le confort, l’accès et l’organisation des séjours comptent autant. Voici comment préparer votre appartement à Guéliz avant de publier une annonce ou de déléguer sa gestion.',
    takeaway: 'À Guéliz, travaillez la précision de l’annonce et la fiabilité de l’accueil. Comparez des appartements réellement similaires et construisez un budget après charges, sans déduire votre revenu du seul nom du quartier.',
    sections: [
      { id: 'quartier', title: 'Pourquoi étudier un projet de location à Guéliz ?', paragraphs: ['Le guide touristique officiel Visit Marrakech présente Guéliz comme une partie moderne de la ville, avec des commerces et une vie culturelle. Airbnb propose également une page consacrée aux appartements de vacances à Guéliz. Ces références permettent d’observer une offre existante ; elles ne fournissent pas un recensement des propriétaires ni une garantie de réservations.', 'Pour votre projet, commencez par définir ce que votre adresse permet concrètement : commerces accessibles, parcours d’arrivée, stationnement disponible et environnement du bâtiment. Un appartement bien présenté doit aider le voyageur à comprendre son séjour, sans annoncer des distances ou des prestations non vérifiées.'], links: [{ label: 'Visit Marrakech : présentation officielle de Guéliz', href: 'https://visitmarrakech.com/listing/gueliz/' }, { label: 'Airbnb : appartements de vacances à Guéliz', href: 'https://www.airbnb.fr/gueliz-morocco/stays/apartments' }] },
      { id: 'adresse', title: 'Évaluer l’adresse plutôt que le quartier seul', paragraphs: ['Visitez le logement aux heures où les voyageurs seront présents. Vérifiez les bruits, la lumière et le trajet depuis la rue jusqu’à la porte. Décrivez l’étage, l’ascenseur et les accès partagés. Une adresse à Guéliz peut présenter des conditions différentes d’une autre rue du même quartier.', 'Si vous mentionnez un parking ou la proximité d’un repère, contrôlez les conditions d’utilisation et le trajet réel. Dans l’annonce, distinguez une place privative d’un stationnement public. Pour l’arrivée, préparez une consigne qui fonctionne aussi lorsque le propriétaire n’est pas présent.'], bullets: ['Tester l’entrée de l’immeuble et les clés.', 'Documenter l’étage et l’accès par ascenseur ou escalier.', 'Vérifier le bruit et expliquer les contraintes utiles.', 'Préciser les conditions de stationnement proposées.'] },
      { id: 'equipements', title: 'Préparer un appartement facile à utiliser', paragraphs: ['Priorisez les équipements annoncés : couchages confortables, eau chaude, connexion Internet et cuisine fonctionnelle. Testez la climatisation lorsque vous la proposez. Une liste d’équipements longue ne remplace pas leur fonctionnement réel à chaque séjour.', 'Photographiez les pièces et les détails qui expliquent le logement. Montrez la configuration des couchages, le bureau s’il existe et les espaces réellement accessibles. Une annonce fidèle limite les malentendus ; un équipement ou une vue ne doit pas être suggéré si le voyageur ne peut pas en bénéficier.'], links: [{ label: 'Créer une annonce Airbnb au Maroc', href: '/fr/blog/creer-annonce-airbnb-maroc' }] },
      { id: 'gestion', title: 'Organiser les séjours et les rotations', paragraphs: ['Définissez qui répond aux messages, prépare l’arrivée et contrôle l’appartement après le départ. La coordination du ménage et du linge doit correspondre à vos horaires d’arrivée. Si plusieurs réservations se suivent, gardez un temps réaliste pour remettre le logement en état.', 'Pour une gestion à distance, prévoyez un contact local et un seuil d’autorisation pour les dépenses. Documentez les incidents et les interventions. Chez COOHOSTY, la gestion COHOST à Marrakech est proposée à 20 % du montant des réservations ; les prestations et les modalités sont précisées au devis.'], links: [offer] },
      { id: 'budget', title: 'Comparer les annonces et construire votre budget', paragraphs: ['Sélectionnez des appartements comparables par capacité, équipements, accès et emplacement. Observez des dates communes et les conditions de réservation. Un prix affiché n’indique pas le revenu effectivement réalisé, et une date indisponible peut être bloquée par le propriétaire.', 'Votre budget doit distinguer recettes, frais de plateforme, gestion, ménage, consommables, entretien et charges du logement. Testez un mois avec moins de réservations et une dépense imprévue. Faites confirmer les démarches applicables à votre bien avant de lancer l’activité.'], links: [{ label: 'Comparer conciergerie et gestion autonome', href: '/fr/blog/conciergerie-ou-gestion-autonome-airbnb-maroc' }, { label: 'Les formalités d’accueil des voyageurs', href: '/fr/blog/fiche-de-police-airbnb-maroc' }] },
    ],
    faq: [{ question: 'Guéliz garantit-il une bonne rentabilité Airbnb ?', answer: 'Non. Le résultat dépend du logement, de ses coûts, de ses disponibilités et des réservations obtenues. Le quartier est un critère à étudier avec ces éléments.' }, { question: 'Faut-il une place de parking ?', answer: 'Cela dépend de votre logement et du séjour proposé. Si vous annoncez un parking, précisez s’il est privé, partagé ou public et vérifiez ses conditions d’accès.' }, { question: 'Quelle est la commission COOHOSTY à Guéliz ?', answer: 'Pour la gestion COHOST à Marrakech, notre commission est de 20 % du montant des réservations. Le devis précise les modalités de calcul, les prestations et les dépenses complémentaires.' }, { question: 'Peut-on gérer un appartement à Guéliz depuis l’étranger ?', answer: 'Il faut une organisation locale fiable pour les accès, le ménage et les incidents, avec un suivi des dépenses et des interventions. La mission de chaque personne doit être définie.' }],
    related: ['location-courte-duree-hivernage-marrakech', 'location-courte-duree-medina-marrakech', 'conciergerie-airbnb-marrakech'],
  },
  {
    ...dates, slug: 'location-courte-duree-hivernage-marrakech', category: 'Hivernage · Marrakech',
    title: 'Airbnb à l’Hivernage : les points clés pour louer son appartement à Marrakech',
    seoTitle: 'Airbnb Hivernage Marrakech : gérer son appartement',
    description: 'Location courte durée à l’Hivernage : résidence, confort, accueil et dépenses. Préparez un appartement Airbnb avec une organisation adaptée au logement.',
    intro: 'Vous possédez un appartement à l’Hivernage et souhaitez le proposer pour des séjours courts ? Le quartier est connu pour ses hôtels et ses lieux de sortie, mais votre offre doit reposer sur les qualités réelles du logement. Le fonctionnement de la résidence, le confort et la préparation de l’accueil méritent une attention particulière. Voici une méthode pour construire votre projet à Marrakech.',
    takeaway: 'À l’Hivernage, rendez les conditions du séjour précises : accès, équipements, espaces partagés et bruit éventuel. Une bonne organisation se juge sur ce que le voyageur trouve réellement à son arrivée.',
    sections: [
      { id: 'quartier', title: 'Comprendre le contexte de l’Hivernage', paragraphs: ['Visit Marrakech présente l’Hivernage comme un secteur résidentiel et touristique où se trouvent des hôtels, des restaurants et des lieux de sortie. Ce contexte permet de décrire l’environnement d’un appartement. Il ne permet pas de promettre une clientèle, un taux d’occupation ou un prix à la nuitée.', 'Étudiez l’adresse de votre bien et ce qui le distingue sans superlatifs : disposition, capacité, terrasse, stationnement ou environnement. Vérifiez chaque caractéristique avant de l’inscrire dans l’annonce. Une localisation connue ne dispense pas de préciser les contraintes du logement.'], links: [{ label: 'Visit Marrakech : le quartier de l’Hivernage', href: 'https://visitmarrakech.com/en/listing/lhivernage/' }] },
      { id: 'residence', title: 'Vérifier les règles et les accès de la résidence', paragraphs: ['Avant d’ouvrir le calendrier, documentez le fonctionnement de l’immeuble : entrée, remise des clés, stationnement et conditions d’accès aux espaces communs. Faites confirmer les règles applicables à votre projet auprès des interlocuteurs compétents. La présence d’une piscine dans une résidence ne signifie pas automatiquement que vos voyageurs pourront l’utiliser.', 'Précisez dans l’annonce les espaces inclus, les horaires ou restrictions connus et les éventuels frais. Transmettez aux voyageurs les consignes nécessaires. Si un gardien intervient dans l’arrivée, assurez-vous que son rôle est convenu et qu’une solution est prévue en cas d’absence.'], bullets: ['Identifier les accès et les interlocuteurs de la résidence.', 'Confirmer les conditions d’usage des espaces communs.', 'Préparer une remise des clés fiable.', 'Préciser les règles utiles aux voyageurs.'] },
      { id: 'confort', title: 'Faire correspondre l’annonce au confort réel', paragraphs: ['Testez les équipements avant de publier : climatisation, eau chaude, Internet, literie et appareils de cuisine. Le voisinage d’un hôtel ou d’un restaurant ne constitue pas un service inclus dans votre logement. Expliquez précisément ce qui est fourni et ce qui relève du quartier.', 'Évaluez le bruit aux heures pertinentes et décrivez les contraintes. Une terrasse, un balcon ou une vue peuvent être des atouts, mais doivent être représentés fidèlement. Évitez les expressions comme « calme absolu » si vous ne pouvez pas les soutenir dans les conditions normales du séjour.'], links: [{ label: 'Préparer les photos et la description Airbnb', href: '/fr/blog/creer-annonce-airbnb-maroc' }] },
      { id: 'organisation', title: 'Construire une organisation d’accueil régulière', paragraphs: ['Un séjour préparé repose sur des consignes simples et des responsabilités claires. Définissez qui transmet les informations, répond aux questions et intervient si les clés ou un appareil posent problème. Prévoyez le ménage et un contrôle du logement avant chaque arrivée.', 'Pour un propriétaire absent, convenez d’un suivi des opérations et des dépenses. COOHOSTY propose la gestion COHOST à Marrakech avec une commission de 20 % du montant des réservations. Le devis définit le périmètre, les modalités de calcul et les dépenses complémentaires.'], links: [offer] },
      { id: 'budget', title: 'Suivre le revenu après charges', paragraphs: ['Comparez votre appartement à des biens proches par capacité et équipements, sur des dates communes. Distinguez le tarif demandé du revenu réalisé. Une offre mieux équipée peut aussi demander davantage d’entretien ou de consommables : le prix seul ne suffit pas à décider.', 'Suivez les nuits proposées, les réservations, les frais et les dépenses. Gardez vos dates personnelles séparées des dates ouvertes aux voyageurs. Votre projet doit également intégrer les démarches administratives et fiscales applicables, à confirmer pour votre situation.'], links: [{ label: 'Comprendre les frais Airbnb', href: '/fr/blog/commission-airbnb-maroc' }, { label: 'Choisir une société de conciergerie', href: '/fr/blog/choisir-societe-conciergerie-maroc' }] },
    ],
    faq: [{ question: 'L’Hivernage convient-il uniquement aux logements de luxe ?', answer: 'Le projet doit être étudié à partir des caractéristiques de votre logement et de ses coûts. Le nom du quartier ne fixe pas à lui seul une catégorie, une clientèle ou un prix.' }, { question: 'Puis-je annoncer la piscine de ma résidence ?', answer: 'Confirmez d’abord que vos voyageurs pourront y accéder, puis précisez les conditions, horaires et restrictions. N’annoncez pas un équipement dont l’accès n’est pas établi.' }, { question: 'Quelle commission applique COOHOSTY à Marrakech ?', answer: 'Notre commission pour la gestion COHOST à Marrakech est de 20 % du montant des réservations. Les modalités et les dépenses complémentaires figurent dans le devis.' }, { question: 'Comment gérer une arrivée tardive ?', answer: 'Préparez un accès accepté par la résidence, des instructions compréhensibles et un contact disponible selon les horaires convenus. Testez la procédure avant la première réservation.' }],
    related: ['location-courte-duree-gueliz-marrakech', 'location-courte-duree-palmeraie-marrakech', 'conciergerie-airbnb-marrakech'],
  },
  {
    ...dates, slug: 'location-courte-duree-medina-marrakech', category: 'Médina · Marrakech',
    title: 'Location courte durée dans la Médina de Marrakech : préparer son riad et ses arrivées',
    seoTitle: 'Airbnb Médina Marrakech : guide pour louer un riad',
    description: 'Riad ou logement dans la Médina de Marrakech : préparez les accès, les arrivées, les espaces et la gestion des séjours avant de publier sur Airbnb.',
    intro: 'La Médina de Marrakech offre un cadre particulier pour un projet de location courte durée. Pour un riad ou un logement de caractère, l’organisation doit tenir compte des accès, de la disposition du bâtiment et des espaces réellement proposés. Ce guide aide les propriétaires à préparer une annonce fidèle et un parcours d’arrivée utilisable par les voyageurs.',
    takeaway: 'Dans la Médina, préparez le trajet jusqu’au logement autant que le logement lui-même. Décrivez les espaces, les escaliers et les services de façon précise, puis répartissez les opérations d’accueil et d’entretien.',
    sections: [
      { id: 'cadre', title: 'Présenter le cadre de la Médina sans exagérer la promesse', paragraphs: ['Les organismes touristiques officiels décrivent la Médina comme le centre historique de Marrakech, avec ses ruelles, ses souks et ses riads. Ce cadre peut être présenté dans votre annonce, à condition de distinguer les lieux du quartier et les espaces de votre propre logement.', 'Le mot « riad » ne suffit pas à expliquer ce que le voyageur réserve. Indiquez s’il dispose du logement entier ou d’une partie du bâtiment, si le patio est partagé et quels services sont inclus. Photographiez les espaces accessibles avec une description cohérente.'], links: [{ label: 'Visit Marrakech : la Médina de Marrakech', href: 'https://visitmarrakech.com/en/listing/la-medina-de-marrakech/' }, { label: 'Office National Marocain du Tourisme : Marrakech', href: 'https://visitmorocco.com/fr/voyage/marrakech' }] },
      { id: 'acces', title: 'Préparer un parcours d’arrivée compréhensible', paragraphs: ['Pour votre adresse, identifiez le point de dépose possible et le trajet à pied jusqu’à la porte. Testez les instructions avec quelqu’un qui ne connaît pas les lieux. Un repère clair, des indications concises et un contact joignable permettent d’organiser l’arrivée sans dépendre uniquement d’une adresse écrite.', 'Précisez les contraintes utiles avant la réservation : parcours piéton, escaliers ou difficulté avec des bagages volumineux. Si un accueil accompagné est prévu, définissez le point de rendez-vous, les horaires et le traitement des retards. Une procédure doit rester praticable à l’heure réelle d’arrivée.'], bullets: ['Vérifier le point de dépose pour l’adresse concernée.', 'Documenter le trajet jusqu’à la porte.', 'Préciser les escaliers et les espaces partagés.', 'Prévoir un contact et une solution en cas de retard.'] },
      { id: 'espaces', title: 'Décrire le bâtiment et ses équipements', paragraphs: ['Expliquez la disposition des pièces, la répartition des couchages et les accès aux terrasses ou patios. Si des escaliers sont nécessaires, mentionnez-les. Ne présentez pas un espace commun comme un espace privatif et n’annoncez pas un service assuré par un voisin comme une prestation de votre hébergement.', 'Vérifiez l’éclairage, les serrures, l’eau chaude et les équipements proposés. Pour les espaces extérieurs, prévoyez une information adaptée à leur usage. L’objectif est de permettre aux voyageurs de choisir un logement correspondant à leurs besoins, avec une promesse que vous pourrez tenir.'], links: [{ label: 'Créer une annonce claire et fidèle', href: '/fr/blog/creer-annonce-airbnb-maroc' }] },
      { id: 'gestion', title: 'Coordonner le ménage, l’accueil et les formalités', paragraphs: ['Définissez le temps nécessaire au ménage et au contrôle de chaque espace. Un bâtiment avec plusieurs niveaux peut demander une organisation différente d’un appartement. Précisez qui vérifie le linge, les équipements et les accès avant l’arrivée suivante.', 'Les démarches relatives au logement et à l’accueil des voyageurs doivent être confirmées pour votre situation. Si vous déléguez, écrivez les responsabilités de chacun et les justificatifs attendus. La publication d’une annonce ne valide pas automatiquement les conditions d’exploitation.'], links: [{ label: 'Préparer les formalités d’accueil au Maroc', href: '/fr/blog/fiche-de-police-airbnb-maroc' }] },
      { id: 'budget', title: 'Évaluer la gestion et le budget de votre riad', paragraphs: ['Construisez votre budget avec les dépenses réellement nécessaires au bâtiment : ménage, linge, consommables, entretien et interventions. Comparez des hébergements similaires dans leur capacité et leur organisation, sans reprendre directement le prix d’un établissement proposant d’autres prestations.', 'Pour la gestion COHOST à Marrakech, COOHOSTY applique une commission de 20 % du montant des réservations. Le devis précise la base de calcul, le périmètre de la mission et les dépenses complémentaires. Une estimation de recettes doit présenter ses hypothèses et rester distincte d’une garantie de revenus.'], links: [offer] },
    ],
    faq: [{ question: 'Comment préciser l’accès à un riad dans la Médina ?', answer: 'Documentez le point de dépose et le trajet jusqu’au logement, puis testez vos instructions. Précisez les contraintes utiles et le contact prévu pour l’arrivée.' }, { question: 'Faut-il proposer le riad entier ?', answer: 'Votre annonce doit indiquer exactement les espaces réservés au voyageur et ceux qui sont partagés. Les conditions du projet et les démarches applicables doivent être confirmées pour votre situation.' }, { question: 'Quelle commission pour une gestion COOHOSTY à Marrakech ?', answer: 'La commission COHOST à Marrakech est de 20 % du montant des réservations. Le devis détaille les modalités, les prestations et les dépenses complémentaires.' }, { question: 'Peut-on louer sans être présent sur place ?', answer: 'Une organisation locale est nécessaire pour les accès, le ménage et les incidents. Définissez les responsabilités, les horaires convenus et le suivi des opérations.' }],
    related: ['location-courte-duree-gueliz-marrakech', 'location-courte-duree-palmeraie-marrakech', 'fiche-de-police-airbnb-maroc'],
  },
  {
    ...dates, slug: 'location-courte-duree-palmeraie-marrakech', category: 'Palmeraie · Marrakech',
    title: 'Airbnb dans la Palmeraie de Marrakech : organiser la location courte durée de sa villa',
    seoTitle: 'Airbnb Palmeraie Marrakech : préparer sa villa',
    description: 'Villa Airbnb dans la Palmeraie : accès, piscine, jardin, entretien et budget. Organisez votre location courte durée à Marrakech avant les premiers séjours.',
    intro: 'Vous souhaitez proposer une villa dans la Palmeraie de Marrakech pour des séjours courts ? Les espaces extérieurs et la capacité du logement demandent une préparation attentive. L’entretien, les déplacements et le suivi sur place doivent être intégrés au projet dès le départ. Voici les points à examiner avant d’ouvrir votre calendrier ou de confier la gestion de votre villa.',
    takeaway: 'Pour une villa dans la Palmeraie, calculez les dépenses d’exploitation et préparez les interventions locales. Une piscine, un jardin ou une grande capacité constituent aussi des équipements et des opérations à entretenir.',
    sections: [
      { id: 'secteur', title: 'Étudier votre adresse dans la Palmeraie', paragraphs: ['La Palmeraie figure dans les ressources touristiques officielles de Marrakech, et des villas du secteur sont proposées sur Airbnb. Cela confirme une offre observable, sans fournir un nombre exact de propriétaires ni un résultat financier applicable à votre bien.', 'Décrivez le logement et son environnement à partir de vérifications concrètes : trajet jusqu’à la propriété, accès, stationnement et services réellement disponibles. Une adresse dans la Palmeraie ne permet pas de généraliser un temps de transport ou une distance pour toutes les villas.'], links: [{ label: 'Visit Marrakech : la Palmeraie', href: 'https://mice.visitmarrakech.com/listing/palmeraie-de-marrakech/' }, { label: 'Exemple d’une villa proposée sur Airbnb dans la Palmeraie', href: 'https://www.airbnb.fr/rooms/1688529214217737860' }] },
      { id: 'arrivee', title: 'Organiser les accès et les déplacements', paragraphs: ['Vérifiez l’itinéraire d’arrivée, l’entrée de la propriété et les conditions d’accès à une résidence lorsque c’est le cas. Préparez les informations qui permettent au voyageur et à son chauffeur d’identifier la bonne entrée. Convenez d’une procédure pour les retards et les incidents d’accès.', 'Si vous proposez un transfert ou une livraison, précisez qui les assure et comment ils sont facturés. Distinguez ces services des prestations incluses dans le logement. Une information claire sur les déplacements permet au voyageur de préparer son séjour selon son organisation.'], bullets: ['Tester l’itinéraire et les accès.', 'Définir la remise des clés et le stationnement.', 'Identifier le contact local et ses horaires.', 'Clarifier les services de transport éventuellement proposés.'] },
      { id: 'exterieurs', title: 'Préparer la piscine, le jardin et les équipements', paragraphs: ['Pour une piscine annoncée, planifiez son entretien et les contrôles nécessaires avec les intervenants adaptés. Informez les voyageurs des règles d’utilisation et des caractéristiques utiles, notamment lorsqu’ils séjournent avec des enfants. Ne présentez pas une piscine comme chauffée si ce service n’est pas réellement disponible.', 'Le jardin, le mobilier extérieur et les équipements de cuisine demandent également un suivi. Fixez la fréquence des interventions et le moment où elles peuvent avoir lieu pendant un séjour. Documentez les opérations afin de pouvoir vérifier que la propriété reste conforme à l’annonce.'] },
      { id: 'rotations', title: 'Prévoir le temps de remise en état d’une villa', paragraphs: ['Évaluez le ménage à partir du nombre de pièces, de salles d’eau et d’espaces réellement utilisés. Définissez qui coordonne le linge, contrôle les équipements et signale un incident après le départ. Évitez de promettre une arrivée trop tôt si le temps de préparation ne le permet pas.', 'Si plusieurs prestataires interviennent, désignez un interlocuteur qui suit l’ensemble. Les achats et réparations doivent être tracés, avec un seuil d’autorisation convenu. Une gestion à distance reste possible à condition de disposer d’une organisation locale claire et d’un suivi compréhensible.'], links: [{ label: 'Choisir une société de conciergerie pour son logement', href: '/fr/blog/choisir-societe-conciergerie-maroc' }] },
      { id: 'budget', title: 'Construire un budget après dépenses', paragraphs: ['Séparez les frais réguliers, les interventions ponctuelles et les dépenses liées à chaque séjour. Testez plusieurs scénarios de recettes en gardant les hypothèses visibles. Une villa avec davantage d’équipements peut demander un budget d’entretien plus important ; les recettes seules ne décrivent pas le résultat.', 'La commission COOHOSTY pour la gestion COHOST à Marrakech est de 20 % du montant des réservations. Le devis précise le calcul, le périmètre et les dépenses complémentaires. Avant le lancement, faites confirmer les démarches applicables au logement et à l’accueil des voyageurs.'], links: [offer, { label: 'Comprendre les frais Airbnb et le versement de l’hôte', href: '/fr/blog/commission-airbnb-maroc' }] },
    ],
    faq: [{ question: 'Une piscine garantit-elle davantage de réservations ?', answer: 'Non. Elle est un équipement à présenter fidèlement et à entretenir. Les réservations dépendent aussi du logement, des tarifs, des disponibilités et de la demande.' }, { question: 'Comment estimer l’entretien d’une villa ?', answer: 'Demandez des propositions adaptées aux espaces et équipements réels, puis distinguez l’entretien régulier, les interventions ponctuelles et les dépenses de chaque séjour.' }, { question: 'Quelle commission applique COOHOSTY dans la Palmeraie ?', answer: 'Pour la gestion COHOST à Marrakech, notre commission est de 20 % du montant des réservations. Les modalités et dépenses complémentaires sont précisées au devis.' }, { question: 'Peut-on confier la gestion depuis l’étranger ?', answer: 'Prévoyez un contact local, un suivi des opérations et un accord sur les dépenses. Les accès, le ménage et les interventions doivent être organisés avant les premières réservations.' }],
    related: ['location-courte-duree-hivernage-marrakech', 'location-courte-duree-medina-marrakech', 'conciergerie-airbnb-marrakech'],
  },
];
