export type BlogSection = {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
  sources?: string[];
  links?: { label: string; href: string }[];
  table?: { headers: string[]; rows: string[][]; caption: string };
};
export type BlogPost = {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  category: string;
  intro: string;
  takeaway: string;
  published: string;
  modified: string;
  note?: string;
  sections: BlogSection[];
  faq: { question: string; answer: string }[];
  related: string[];
};

export const blogSources: Record<string, { title: string; url: string }> = {
  tourism: { title: 'Ministère du Tourisme — cadre juridique de l’hébergement touristique', url: 'https://mtaess.gov.ma/fr/tourisme/metiers-tourisme/hebergement-touristique/' },
  police: { title: 'Décret n° 2-15-865 et modèle du bulletin individuel d’hébergement (PDF officiel)', url: 'https://mtaess.gov.ma/wp-content/uploads/2025/06/Decret-n%C2%B02-15-865-teledec.pdf' },
  privacy: { title: 'CNDP — guide de conformité des sites web et protection des données', url: 'https://www.cndp.ma/wp-content/uploads/2023/01/CNDP-guide-conformite-sites-web-fr.pdf' },
  tax: { title: 'Code général des impôts 2026 — édition DGI, hébergée par le CRI Casablanca-Settat', url: 'https://casainvest.ma/sites/default/files/2026-02/Code%20impo%CC%82ts%202026.pdf' },
  localTax: { title: 'Direction générale des collectivités territoriales — guide de fiscalité locale', url: 'https://www.collectivites-territoriales.gov.ma/sites/default/files/pnct/2025-05/Fiscalit%C3%A9%20des%20CTs%20VF%2019%2012%202024.pdf' },
  collectedTax: { title: 'Airbnb — lieux où la taxe de séjour est collectée et reversée', url: 'https://www.airbnb.fr/help/article/2509' },
  fees: { title: 'Airbnb — frais de service pour les séjours', url: 'https://www.airbnb.fr/help/article/1857' },
  payout: { title: 'Airbnb — calcul du versement de l’hôte', url: 'https://www.airbnb.fr/help/article/459' },
  lease: { title: 'Loi n° 67-12 — traduction française non officielle publiée par l’Agence urbaine de Tétouan', url: 'https://aute.gov.ma/s/a/library/2023-11-01/b941f00c-28f5-4a1c-8a0c-dcba0d7d0987.pdf' },
  terms: { title: 'Airbnb — conditions de service applicables selon le pays de résidence', url: 'https://www.airbnb.fr/help/article/2908' },
  booking: { title: 'Airbnb — réserver un logement', url: 'https://www.airbnb.fr/help/article/85' },
};

const dates = { published: '2026-10-07', modified: '2026-10-07' };
const complianceNote = 'Ce guide fournit des informations générales. Pour votre logement, faites confirmer les démarches par les autorités compétentes et, selon le sujet, par un juriste ou un expert-comptable au Maroc.';

export const blogPosts: BlogPost[] = [
  {
    ...dates,
    slug: 'fiche-de-police-airbnb-maroc',
    title: 'Fiche de police Airbnb au Maroc : démarches et modèle officiel',
    seoTitle: 'Fiche de police Airbnb Maroc : guide et PDF officiel',
    description: 'Fiche de police Airbnb au Maroc : bulletin individuel d’hébergement, PDF officiel, démarches à confirmer et organisation de l’accueil des voyageurs.',
    category: 'Formalités',
    intro: 'Avant une première arrivée, beaucoup de propriétaires cherchent une « fiche de police Airbnb Maroc » à télécharger. Le document à connaître est le bulletin individuel d’hébergement. Pour organiser correctement l’accueil, il faut distinguer le formulaire, la déclaration des voyageurs et le droit d’exploiter le logement.',
    takeaway: 'Consultez le bulletin officiel, puis confirmez auprès du service compétent les obligations et le canal de déclaration applicables à votre hébergement. Un PDF rempli ne constitue pas une autorisation de louer.',
    note: complianceNote,
    sections: [
      { id: 'definition', title: 'Qu’est-ce que la fiche de police pour un Airbnb au Maroc ?', paragraphs: ['L’expression « fiche de police » désigne couramment un document utilisé pour identifier les personnes hébergées. Le décret n° 2-15-865 du 9 juin 2016 encadre la télédéclaration des données des clients des établissements et autres formes d’hébergement touristique et comporte le modèle du bulletin individuel d’hébergement.', 'La démarche ne dépend donc pas uniquement du fait d’avoir une annonce Airbnb. Commencez par faire préciser la catégorie et la situation administrative de votre logement.'], sources: ['police'] },
      { id: 'modele-pdf', title: 'Où trouver le modèle officiel en PDF ?', paragraphs: ['Le ministère du Tourisme met à disposition le décret et son annexe. Le lien ci-dessous ouvre le document officiel complet : consultez l’annexe pour retrouver le modèle du bulletin. Vous pouvez enregistrer ce PDF depuis votre navigateur.', 'Utilisez cette référence plutôt qu’un formulaire trouvé sur les réseaux sociaux. Avant de l’intégrer à votre procédure d’accueil, demandez si votre service local exige ce modèle, une saisie électronique ou une démarche complémentaire.'], links: [{ label: 'Consulter le PDF officiel et le modèle en annexe', href: blogSources.police.url }] },
      { id: 'avant-arrivee', title: 'Les vérifications à faire avant la première arrivée', paragraphs: ['Préparez un dossier par logement afin de ne pas découvrir les formalités lorsque les voyageurs sont déjà devant la porte. Voici une méthode d’organisation à adapter après confirmation des autorités :'], bullets: ['Faire confirmer la situation du logement auprès du service territorial du tourisme et des autorités compétentes.', 'Demander quel service reçoit les déclarations et quelle procédure s’applique à votre cas.', 'Vérifier les conditions d’accès au système de télédéclaration, lorsqu’il est applicable.', 'Faire préciser les délais, les informations à recueillir et les règles de conservation.', 'Désigner la personne qui contrôle les informations et effectue les démarches lors de chaque arrivée.'], sources: ['tourism'] },
      { id: 'organisation', title: 'Comment organiser la collecte des informations ?', paragraphs: ['Après validation de votre procédure, préparez les champs correspondant au modèle accepté. Vérifiez les informations avec les pièces présentées par les voyageurs, puis traitez les données selon les consignes du service compétent. Ne supposez pas qu’une seule personne renseignée couvre automatiquement tout le groupe.', 'Vous pouvez utiliser une liste de contrôle interne : réservation identifiée, informations vérifiées, démarche effectuée, preuve conservée lorsqu’elle est prévue. Cette liste sert à suivre le travail ; elle ne remplace pas le bulletin ou la déclaration.', 'Si une arrivée a lieu tard le soir, prévoyez à l’avance qui reste disponible. Une boîte à clés facilite la remise des clés, mais votre organisation doit aussi couvrir les formalités d’accueil.'] },
      { id: 'donnees-personnelles', title: 'Protéger les données personnelles des voyageurs', paragraphs: ['Les informations d’identité demandent une attention particulière. La loi marocaine n° 09-08 encadre le traitement des données personnelles ; la CNDP publie notamment des recommandations sur l’information des personnes, la sécurité et les formalités des traitements en ligne.', 'Limitez les accès aux personnes chargées de la démarche. Évitez les dossiers partagés ouverts à tous et les copies de pièces envoyées sans contrôle dans plusieurs messageries. Faites valider votre méthode de collecte, la durée de conservation et les éventuels transferts de données à l’étranger.'], sources: ['privacy'] },
      { id: 'erreurs', title: 'Les erreurs fréquentes à éviter', paragraphs: ['La première erreur consiste à confondre la déclaration des clients avec l’autorisation d’exploiter. La seconde est de reprendre une procédure française ou celle d’un autre logement sans vérifier son application locale.', 'Enfin, si vous déléguez la gestion, précisez les responsabilités par écrit : qui recueille les données, qui les vérifie, qui les transmet et comment le propriétaire suit les démarches. Demandez au prestataire ce que son contrat couvre réellement.'], links: [{ label: 'Comprendre le rôle d’une conciergerie Airbnb à Marrakech', href: '/fr/blog/conciergerie-airbnb-marrakech' }, { label: 'Préparer les questions fiscales de votre location', href: '/fr/blog/fiscalite-taxes-airbnb-maroc' }] },
    ],
    faq: [
      { question: 'Où télécharger une fiche de police Airbnb Maroc en PDF ?', answer: 'Le ministère du Tourisme publie le décret n° 2-15-865 avec le modèle du bulletin individuel d’hébergement en annexe. Le lien officiel figure dans ce guide.' },
      { question: 'La fiche de police suffit-elle pour louer sur Airbnb ?', answer: 'Non. Le bulletin d’hébergement, la déclaration des voyageurs et les autorisations éventuelles sont des démarches distinctes. Faites confirmer la situation de votre logement.' },
      { question: 'Une conciergerie peut-elle effectuer les formalités ?', answer: 'Demandez au prestataire si cette mission est incluse et selon quelles conditions. La délégation doit respecter la procédure applicable, les accès autorisés et la protection des données.' },
    ],
    related: ['fiscalite-taxes-airbnb-maroc', 'sous-location-airbnb-maroc', 'conciergerie-airbnb-marrakech'],
  },
  {
    ...dates,
    slug: 'fiscalite-taxes-airbnb-maroc',
    title: 'Fiscalité et taxes Airbnb au Maroc : guide pour les propriétaires',
    seoTitle: 'Fiscalité Airbnb Maroc : impôts, TVA et taxe de séjour',
    description: 'Comprenez les questions fiscales d’un Airbnb au Maroc : revenus locatifs, TVA, taxe de séjour et documents à préparer pour votre expert-comptable.',
    category: 'Fiscalité',
    intro: 'Un versement Airbnb ne représente pas automatiquement votre bénéfice, et les frais de plateforme ne remplacent pas vos impôts. Pour comprendre la fiscalité d’une location au Maroc, commencez par identifier votre statut et la nature réelle de votre activité.',
    takeaway: 'Séparez les recettes, les commissions, les dépenses et les taxes. Faites valider le régime fiscal de votre activité avant d’appliquer un taux trouvé en ligne.',
    note: complianceNote,
    sections: [
      { id: 'regime-fiscal', title: 'Quel régime fiscal pour les revenus Airbnb au Maroc ?', paragraphs: ['Le Code général des impôts distingue notamment les revenus fonciers des revenus professionnels. Son article 61 définit les revenus fonciers lorsqu’ils ne relèvent pas des revenus professionnels. La qualification doit être examinée selon l’activité et le statut de l’exploitant ; le nom de la plateforme ne suffit pas.', 'Demandez à votre expert-comptable de qualifier votre activité avant de déterminer l’assiette, le taux et les déclarations. Si le logement est exploité par une société, l’analyse diffère de celle d’un propriétaire personne physique.'], sources: ['tax'] },
      { id: 'tva', title: 'La TVA concerne-t-elle une location meublée ?', paragraphs: ['L’article 89 du CGI vise notamment les opérations d’hébergement et les locations de locaux meublés ou garnis parmi les opérations imposables à la TVA. Faites examiner les conditions et les éventuelles exonérations de votre situation, sans transposer les règles d’une location nue.', 'Posez des questions précises : quel traitement pour l’hébergement, les services supplémentaires et les factures des prestataires ? Comment présenter vos prix ? La TVA éventuellement figurant sur les frais de plateforme doit aussi être distinguée de celle liée à votre activité.'], sources: ['tax'] },
      { id: 'taxe-sejour', title: 'Taxe de séjour : pourquoi le montant dépend du logement', paragraphs: ['Le guide de la fiscalité locale publié par la Direction générale des collectivités territoriales présente la taxe de séjour prévue par la loi n° 47-06. Pour les hébergements concernés, elle s’ajoute au prix d’hébergement et se calcule par personne et par nuitée. Les tarifs dépendent de la catégorie et de l’arrêté de la commune.', 'Il n’existe donc pas un montant à recopier pour tous les Airbnb du Maroc. Faites confirmer la catégorie de votre hébergement, le tarif communal, les exonérations et les échéances de déclaration et de versement.'], sources: ['localTax'] },
      { id: 'collecte-airbnb', title: 'Airbnb collecte-t-il automatiquement les taxes au Maroc ?', paragraphs: ['La collecte automatique par Airbnb concerne des lieux et des taxes déterminés. Lors de la consultation de sa liste officielle le 7 octobre 2026, le Maroc n’y figurait pas. N’en déduisez pas que votre hébergement est exonéré : vérifiez les taxes affichées pour votre annonce et les obligations auprès des services compétents.', 'Une ligne de taxe sur une réservation n’établit pas, à elle seule, que tous vos impôts ont été déclarés et payés. Identifiez qui collecte, qui reçoit les fonds et qui doit les reverser.'], sources: ['collectedTax'] },
      { id: 'documents', title: 'Les documents à préparer pour votre comptabilité', paragraphs: ['Un dossier mensuel facilite le contrôle des recettes et évite de reconstituer toute l’année à partir des seuls mouvements bancaires. Conservez des pièces cohérentes entre elles et demandez à votre comptable le format dont il a besoin.'], bullets: ['Historique des réservations, annulations et remboursements.', 'Relevés Airbnb détaillant les revenus, les frais et les versements.', 'Factures de conciergerie, de ménage, de maintenance et autres justificatifs.', 'Relevés bancaires et détails des conversions de devises, le cas échéant.', 'Documents relatifs aux taxes collectées et aux versements effectués.', 'Bail ou titre de propriété, contrat de gestion et éléments du statut d’exploitation.'] },
      { id: 'suivi-recettes', title: 'Construire un suivi mensuel utile', paragraphs: ['Pour piloter votre logement, partez des recettes des séjours, puis distinguez les remboursements, les frais de plateforme, les honoraires de gestion et les dépenses d’exploitation. Ajoutez les sommes encaissées pour le compte d’un tiers dans une colonne distincte afin de ne pas les confondre avec votre marge.', 'Ce tableau sert au suivi économique. Il ne détermine pas automatiquement le revenu imposable : la déductibilité des charges et le traitement des taxes dépendent du régime retenu. Faites rapprocher vos chiffres avec les déclarations par votre comptable.'], links: [{ label: 'Comprendre le calcul de la commission Airbnb en dirhams', href: '/fr/blog/commission-airbnb-maroc' }] },
      { id: 'proprietaire-etranger', title: 'Vous vivez à l’étranger ou êtes MRE ?', paragraphs: ['Indiquez à votre conseiller votre pays de résidence fiscale, le détenteur du logement et la personne qui exploite l’activité. Demandez-lui d’examiner les obligations marocaines et celles de votre pays de résidence, ainsi que la convention fiscale éventuellement applicable.', 'Avant de déléguer, prévoyez également la fréquence des relevés et la transmission des justificatifs. Une bonne gestion quotidienne doit permettre au propriétaire de retrouver ses documents sans dépendre d’échanges dispersés.'] },
    ],
    faq: [
      { question: 'Existe-t-il un taux d’impôt unique pour tous les Airbnb au Maroc ?', answer: 'Non. La qualification des revenus, le statut de l’exploitant et les règles applicables à l’activité doivent être examinés avant le calcul.' },
      { question: 'La commission Airbnb est-elle un impôt ?', answer: 'Non. Elle rémunère la plateforme. Les impôts et taxes constituent des obligations distinctes.' },
      { question: 'Quel est le montant de la taxe de séjour à Marrakech ?', answer: 'Demandez le tarif communal correspondant à la catégorie de votre hébergement et les exonérations éventuelles. Le montant appliqué à un autre établissement ne suffit pas à déterminer le vôtre.' },
    ],
    related: ['commission-airbnb-maroc', 'fiche-de-police-airbnb-maroc', 'airbnb-maroc-definition'],
  },
  {
    ...dates,
    slug: 'commission-airbnb-maroc',
    title: 'Commission Airbnb au Maroc : frais et calcul en dirhams',
    seoTitle: 'Commission Airbnb Maroc : frais et exemples en dirhams',
    description: 'Commission Airbnb au Maroc : comprenez les frais hôte, calculez un versement en MAD et distinguez frais Airbnb, taxes et honoraires de conciergerie.',
    category: 'Revenus & frais',
    intro: 'Combien Airbnb prélève-t-il sur une réservation au Maroc ? Pour répondre, regardez la structure tarifaire de votre compte et le détail de la réservation. Le montant annoncé aux voyageurs, le versement reçu et le bénéfice du propriétaire sont trois chiffres différents.',
    takeaway: 'Vérifiez les frais dans le détail de chaque transaction. Pour prévoir votre marge, ajoutez ensuite les coûts de gestion, d’exploitation et les obligations fiscales.',
    sections: [
      { id: 'frais-hote', title: 'Quel pourcentage de commission Airbnb faut-il prévoir ?', paragraphs: ['Au 7 octobre 2026, Airbnb décrit une transition vers les frais uniques, déduits du versement de l’hôte : généralement 15,5 %, avec des variations. Les frais partagés, généralement 3 % côté hôte, peuvent encore concerner certaines réservations selon la transition du compte.', 'Avant de préparer votre budget, ouvrez plusieurs transactions récentes et relevez les frais réellement affichés. Conservez vos notifications de changement tarifaire pour comprendre les différences entre anciennes et nouvelles réservations.'], sources: ['fees'] },
      { id: 'base-calcul', title: 'Sur quel montant la commission est-elle calculée ?', paragraphs: ['La base comprend les nuits et les frais supplémentaires de l’hôte, notamment le ménage, hors taxes et frais voyageur. Les frais indiqués incluent la TVA lorsqu’elle s’applique.', 'Pour votre contrôle mensuel, notez séparément le total payé, la base des frais et le versement reçu. Cette méthode vous évite de comparer des montants qui ne représentent pas la même chose.'], sources: ['fees'] },
      { id: 'exemple-dirhams', title: 'Exemple de calcul en dirhams marocains', paragraphs: ['Voici un exemple pédagogique, sans conversion de devise, versement de co-hôte ni autre ajustement. Il suppose une base de 3 000 MAD et un taux effectif de frais hôte de 15,5 %. Ce taux est une hypothèse de calcul à comparer avec votre transaction.'], table: { caption: 'Exemple illustratif de versement avant autres charges et impôts', headers: ['Élément', 'Calcul', 'Montant'], rows: [['Cinq nuits', '5 × 560 MAD', '2 800 MAD'], ['Frais de ménage facturés', 'Ajout à la base', '200 MAD'], ['Base des frais hôte', '2 800 + 200', '3 000 MAD'], ['Frais hôte supposés', '3 000 × 15,5 %', '465 MAD'], ['Versement après ces frais', '3 000 − 465', '2 535 MAD']] }, sources: ['payout'] },
      { id: 'versement-benefice', title: 'Pourquoi le versement Airbnb n’est pas votre bénéfice', paragraphs: ['Dans cet exemple, les 200 MAD de ménage facturés au voyageur entrent dans la base, mais vous devez aussi régler la prestation réelle de nettoyage. Le versement de 2 535 MAD n’est donc pas une marge nette.', 'Pour évaluer la performance du bien, suivez les dépenses de ménage, de linge, d’électricité, de consommables, de maintenance et de gestion. Prévoyez également le renouvellement des équipements. Examinez ensuite la fiscalité avec votre comptable plutôt que de qualifier tout solde bancaire de bénéfice.'], links: [{ label: 'Lire le guide fiscalité et taxes Airbnb au Maroc', href: '/fr/blog/fiscalite-taxes-airbnb-maroc' }] },
      { id: 'conciergerie', title: 'Commission Airbnb et frais de conciergerie : deux postes distincts', paragraphs: ['Airbnb rémunère ses services de plateforme. Une conciergerie facture les missions définies dans son contrat. Si ces honoraires sont exprimés en pourcentage, demandez quelle base sert au calcul : recettes avant frais de plateforme, montant après frais, avec ou sans ménage.', 'Une offre qui paraît moins chère peut exclure certaines tâches. Comparez aussi les frais de démarrage, les prestations supplémentaires, les conditions de sortie et la fréquence des comptes rendus. COOHOSTY présente ses offres sur devis ; demandez le périmètre et le mode de facturation correspondant à votre logement.'], links: [{ label: 'Découvrir l’offre COHOST de COOHOSTY', href: '/fr/services/cohost' }, { label: 'Comprendre les services d’une conciergerie à Marrakech', href: '/fr/blog/conciergerie-airbnb-marrakech' }] },
      { id: 'controle', title: 'Comment vérifier les frais d’une réservation ?', paragraphs: ['Ouvrez la transaction dans la rubrique Revenus de votre compte Airbnb et comparez les lignes de frais avec le versement. Si vous utilisez un logiciel de gestion, contrôlez également que vos exports correspondent aux chiffres de la plateforme.', 'Pour votre suivi, gardez quatre colonnes distinctes : recettes, frais Airbnb, frais de gestion et autres dépenses. Lorsqu’une différence apparaît, examinez les remboursements, ajustements et versements de co-hôte avant de modifier vos prix. Un rapprochement mensuel permet de repérer les écarts plus tôt.'], sources: ['payout'] },
    ],
    faq: [
      { question: 'Airbnb prend-il toujours 3 % au Maroc ?', answer: 'Non. Airbnb décrit une transition vers les frais uniques, généralement de 15,5 % pour la plupart des hôtes. Votre transaction et les informations de votre compte permettent de vérifier les frais réellement appliqués.' },
      { question: 'Les frais de ménage entrent-ils dans la base de commission ?', answer: 'Les frais de ménage facturés par l’hôte font partie du sous-total servant au calcul des frais hôte, selon la documentation Airbnb.' },
      { question: 'La commission d’une conciergerie est-elle incluse dans les frais Airbnb ?', answer: 'Ce sont deux rémunérations distinctes. Le contrat de gestion doit préciser la base de facturation et les éventuels versements au co-hôte.' },
    ],
    related: ['fiscalite-taxes-airbnb-maroc', 'conciergerie-airbnb-marrakech', 'airbnb-maroc-definition'],
  },
  {
    ...dates,
    slug: 'sous-location-airbnb-maroc',
    title: 'Sous-location Airbnb au Maroc : bail, accord et précautions',
    seoTitle: 'Sous-location Airbnb Maroc : bail et accord du propriétaire',
    description: 'Sous-location Airbnb au Maroc : accord du bailleur, lecture du bail, obligations touristiques et risques à examiner avant de publier une annonce.',
    category: 'Réglementation',
    intro: 'Louer un appartement à l’année puis le proposer sur Airbnb peut sembler simple. Pourtant, payer un loyer ne vous donne pas automatiquement le droit de commercialiser le logement pour des séjours touristiques. Le bail initial, l’accord du propriétaire et les conditions d’exploitation doivent être examinés ensemble.',
    takeaway: 'Faites vérifier votre bail et obtenez un accord explicite adapté au projet avant de publier. L’accord du bailleur ne remplace pas les démarches administratives et fiscales.',
    note: complianceNote,
    sections: [
      { id: 'definition', title: 'Qu’est-ce qu’une sous-location Airbnb ?', paragraphs: ['Dans une sous-location, le locataire met tout ou partie du logement qu’il loue à disposition d’un tiers contre rémunération. Cela diffère d’une gestion pour le compte du propriétaire : une conciergerie peut intervenir par mandat sans devenir locataire du bien.', 'Clarifiez votre rôle dès le départ. Qui détient le bail ? Qui publie l’annonce ? Qui reçoit les recettes et supporte les charges ? Ces réponses doivent être cohérentes avec les contrats, les démarches et le fonctionnement réel du projet.'] },
      { id: 'bail', title: 'Que prévoit la loi n° 67-12 pour le bail initial ?', paragraphs: ['La loi n° 67-12 vise les baux d’habitation ou professionnels, meublés ou non, de plus de trente jours, hors législation particulière. Pour les locaux d’habitation relevant de ce texte, l’article 39 encadre la sous-location : il prévoit notamment un accord écrit du bailleur par acte à date certaine, sauf stipulation contraire du bail.', 'Ce champ concerne l’analyse du bail initial ; il ne signifie pas qu’un séjour touristique de quelques nuits échappe à toute règle. Faites examiner le contrat et la qualification de l’activité par un juriste. La traduction française publiée par l’Agence urbaine de Tétouan est indiquée comme non officielle.'], sources: ['lease'] },
      { id: 'accord', title: 'Que préciser dans l’accord du propriétaire ?', paragraphs: ['Évitez un simple échange oral du type « vous pouvez recevoir des gens ». Présentez le projet réel de location de courte durée et faites rédiger un accord correspondant au bail et au droit applicable.', 'Comme points à discuter avec votre conseil, prévoyez le type de séjours, les plateformes utilisées, la capacité d’accueil, la répartition des frais, les responsabilités et les conditions de fin du projet. Déterminez aussi ce qu’il advient des réservations lorsque le bail prend fin.'], bullets: ['Adresse et périmètre du logement concerné.', 'Usage envisagé et conditions d’exploitation.', 'Modalités financières et répartition des dépenses.', 'Gestion des dommages, de l’assurance et des réclamations.', 'Durée de l’accord et organisation de la sortie.'] },
      { id: 'autorisations', title: 'L’accord du bailleur suffit-il pour exploiter un Airbnb ?', paragraphs: ['Le cadre de l’hébergement touristique et les règles du bail sont deux sujets distincts. Le ministère du Tourisme publie la loi n° 80-14 et ses textes d’application. Faites confirmer les conditions d’exploitation de votre logement auprès des services compétents.', 'Examinez également le règlement de copropriété, les garanties d’assurance et les obligations fiscales. Un propriétaire qui accepte le projet ne peut pas, à lui seul, régler toutes ces questions. Préparez-les avant d’engager des dépenses d’ameublement ou d’accepter des réservations.'], sources: ['tourism'], links: [{ label: 'Préparer les formalités d’accueil des voyageurs', href: '/fr/blog/fiche-de-police-airbnb-maroc' }, { label: 'Comprendre les questions fiscales', href: '/fr/blog/fiscalite-taxes-airbnb-maroc' }] },
      { id: 'risques', title: 'Quels risques sans accord valable ?', paragraphs: ['Pour les situations régies par la loi n° 67-12, l’article 43 prévoit des conséquences pour la sous-location illégale, notamment une procédure d’expulsion et la résiliation des contrats dans les conditions du texte. Faites évaluer le risque correspondant à votre dossier.', 'Au-delà du contrat, un arrêt d’activité peut entraîner des réservations à réorganiser et des frais déjà engagés difficiles à récupérer. Pour votre budget, testez un scénario avec plusieurs semaines sans recettes au lieu de compter sur une occupation permanente.'], sources: ['lease'] },
      { id: 'rentabilite', title: 'Évaluer le projet avant de signer', paragraphs: ['Construisez un budget qui tient compte du loyer fixe, des frais de plateforme, du ménage, des consommables, des charges et de la maintenance. Ajoutez les frais de gestion et faites déterminer le traitement fiscal par votre comptable.', 'Calculez plusieurs scénarios de prix et de nuits louées. Une sous-location crée une obligation de payer le bailleur même lorsqu’aucun voyageur ne réserve. Une estimation commerciale reste une hypothèse et doit être accompagnée d’une réserve de trésorerie adaptée.', 'Si votre objectif consiste surtout à gérer le bien d’un propriétaire, examinez plutôt avec lui un contrat de gestion clairement défini. Cela permet de comparer deux organisations différentes avant de choisir.'], links: [{ label: 'Comprendre la commission Airbnb', href: '/fr/blog/commission-airbnb-maroc' }, { label: 'Découvrir les services COHOST', href: '/fr/services/cohost' }] },
    ],
    faq: [
      { question: 'Puis-je mettre l’appartement que je loue sur Airbnb ?', answer: 'Pas automatiquement. Faites vérifier le bail, les clauses de sous-location, l’accord du bailleur et les règles d’exploitation applicables à votre logement.' },
      { question: 'Un accord oral du propriétaire suffit-il ?', answer: 'Ne vous reposez pas sur un accord oral. Pour les baux d’habitation relevant de la loi n° 67-12, l’article 39 encadre notamment l’accord écrit par acte à date certaine, sauf stipulation contraire du bail.' },
      { question: 'Sous-location et conciergerie sont-elles la même chose ?', answer: 'Non. La sous-location repose sur la mise à disposition d’un bien loué. Une conciergerie peut gérer le logement pour le compte du propriétaire dans le cadre d’un mandat.' },
    ],
    related: ['fiche-de-police-airbnb-maroc', 'fiscalite-taxes-airbnb-maroc', 'conciergerie-airbnb-marrakech'],
  },
  {
    ...dates,
    slug: 'airbnb-maroc-definition',
    title: 'C’est quoi Airbnb au Maroc ? Le guide pour les propriétaires',
    seoTitle: 'C’est quoi Airbnb au Maroc ? Guide propriétaire',
    description: 'Découvrez le fonctionnement d’Airbnb au Maroc côté propriétaire : annonces, réservations, frais, accueil et préparation de votre logement.',
    category: 'Premiers pas',
    intro: 'Airbnb est une plateforme qui met en relation des hôtes et des voyageurs. Au Maroc, un propriétaire peut l’utiliser pour présenter un logement et recevoir des réservations, sous réserve des règles applicables. La plateforme facilite la commercialisation ; l’exploitation du logement demande une organisation à part entière.',
    takeaway: 'Votre annonce constitue la vitrine du logement. Pour accueillir dans de bonnes conditions, préparez aussi les formalités, le budget, le ménage, la maintenance et la communication.',
    sections: [
      { id: 'fonctionnement', title: 'Comment fonctionne une réservation Airbnb ?', paragraphs: ['Le voyageur recherche un logement selon ses dates et ses besoins. Selon les paramètres de l’annonce, il réserve directement avec la réservation instantanée ou adresse une demande à l’hôte. Les informations de l’annonce doivent lui permettre de comprendre ce qu’il réserve.', 'Côté propriétaire, préparez les disponibilités, le prix, les conditions du séjour et les consignes d’arrivée. Après la réservation, assurez le suivi des messages et l’accueil selon le fonctionnement retenu.'], sources: ['booking'] },
      { id: 'roles', title: 'Quelle différence entre Airbnb, l’hôte et la conciergerie ?', paragraphs: ['Airbnb fournit la plateforme ; ses conditions distinguent ce rôle de celui des hôtes qui proposent les hébergements. Le propriétaire ou l’exploitant reste chargé de comprendre ses obligations et de fournir les prestations annoncées.', 'Une conciergerie intervient sur les tâches prévues dans un contrat : par exemple la préparation de l’annonce, la communication et la coordination des opérations. Identifiez clairement le titulaire de l’annonce, les accès au compte et les responsabilités de chaque intervenant.'], sources: ['terms'], links: [{ label: 'C’est quoi une conciergerie Airbnb à Marrakech ?', href: '/fr/blog/conciergerie-airbnb-marrakech' }] },
      { id: 'preparer', title: 'Comment préparer son appartement avant de le publier ?', paragraphs: ['Commencez par une visite méthodique. Vérifiez les équipements, la literie, l’accès au logement et la capacité d’accueil réelle. Faites tester le Wi-Fi, l’eau chaude et la climatisation lorsque ces équipements sont proposés.', 'Les photos et la description doivent correspondre à ce que le voyageur trouvera. Indiquez les contraintes utiles à sa décision : escaliers, absence d’ascenseur, bruit possible ou modalités de stationnement. Une présentation précise limite les malentendus et prépare un accueil plus fluide.'], bullets: ['Inventaire des équipements et contrôle de leur fonctionnement.', 'Photos récentes représentant fidèlement le logement.', 'Consignes d’arrivée faciles à suivre.', 'Organisation du nettoyage et du remplacement du linge.', 'Contact disponible en cas de problème pendant le séjour.'] },
      { id: 'formalites', title: 'Quelles démarches vérifier au Maroc ?', paragraphs: ['Le ministère du Tourisme publie le cadre de l’hébergement touristique, notamment la loi n° 80-14 et ses textes d’application. La publication d’une annonce ne prouve pas que toutes les conditions d’exploitation sont réunies.', 'Avant de recevoir des voyageurs, faites confirmer les démarches adaptées à votre logement. Si vous êtes locataire, faites vérifier le bail et l’accord du propriétaire. Préparez aussi la déclaration des clients et le suivi fiscal avec les interlocuteurs compétents.'], sources: ['tourism'], links: [{ label: 'Guide de la fiche de police et du bulletin d’hébergement', href: '/fr/blog/fiche-de-police-airbnb-maroc' }, { label: 'Précautions pour la sous-location Airbnb au Maroc', href: '/fr/blog/sous-location-airbnb-maroc' }] },
      { id: 'revenus', title: 'Combien peut rapporter un Airbnb au Maroc ?', paragraphs: ['Il n’existe pas de revenu garanti pour un appartement, un riad ou une villa. Pour construire une estimation, étudiez des logements comparables par quartier, capacité, équipements et période. Puis préparez plusieurs scénarios de prix et d’occupation.', 'Votre calcul doit inclure les jours bloqués pour votre usage personnel et les périodes de maintenance. Déduisez les coûts d’exploitation et faites déterminer les obligations fiscales. Le résultat d’une projection sert à décider ; il ne constitue pas une promesse de recettes.'], links: [{ label: 'Calculer les frais de plateforme en dirhams', href: '/fr/blog/commission-airbnb-maroc' }, { label: 'Comprendre la fiscalité Airbnb au Maroc', href: '/fr/blog/fiscalite-taxes-airbnb-maroc' }] },
      { id: 'gerer', title: 'Gérer seul ou déléguer : comment choisir ?', paragraphs: ['La gestion directe demande du temps pour répondre aux messages, suivre les réservations et organiser les changements de voyageurs. Si vous vivez loin du logement, identifiez une personne qui peut intervenir sur place et une solution de remplacement en cas d’absence.', 'Pour comparer une délégation, demandez la liste des missions, les limites de disponibilité et le détail des frais. Vérifiez comment vous recevez les relevés et comment vous autorisez les dépenses. Le bon choix dépend de votre disponibilité, de votre budget et du niveau de suivi souhaité.', 'COOHOSTY propose des offres AUDIT, OPTIMIZE et COHOST. Consultez leur contenu, puis demandez un devis adapté à la situation du logement.'], links: [{ label: 'Découvrir les offres COOHOSTY', href: '/fr#plans' }, { label: 'Demander une estimation pour votre logement', href: '/fr#estimate' }] },
    ],
    faq: [
      { question: 'Airbnb gère-t-il le ménage et la remise des clés ?', answer: 'Ces opérations doivent être organisées par l’hôte ou par un prestataire dans le cadre de sa mission. Une annonce sur la plateforme ne remplace pas cette organisation.' },
      { question: 'Peut-on louer sur Airbnb quand on vit à l’étranger ?', answer: 'Un projet doit prévoir une organisation locale, des contrats adaptés et la vérification des obligations administratives et fiscales. La distance rend le suivi des opérations particulièrement important.' },
      { question: 'Créer une annonce suffit-il pour démarrer ?', answer: 'Non. Préparez le logement et faites confirmer les conditions d’exploitation, les formalités d’accueil et les obligations fiscales applicables.' },
    ],
    related: ['conciergerie-airbnb-marrakech', 'commission-airbnb-maroc', 'fiche-de-police-airbnb-maroc'],
  },
  {
    ...dates,
    slug: 'conciergerie-airbnb-marrakech',
    title: 'C’est quoi une conciergerie Airbnb à Marrakech ?',
    seoTitle: 'Conciergerie Airbnb Marrakech : services et fonctionnement',
    description: 'Comprenez le rôle d’une conciergerie Airbnb à Marrakech : gestion des annonces, accueil, ménage, tarifs et questions à poser avant de déléguer.',
    category: 'Gestion locative',
    intro: 'Une conciergerie Airbnb accompagne un propriétaire dans la gestion de son logement en location de courte durée. À Marrakech, le terme peut couvrir des missions très différentes : création d’annonce, tarification, messages, accueil ou coordination du ménage. Le contrat doit préciser ce qui est réellement pris en charge.',
    takeaway: 'Comparez les missions et les responsabilités avant les pourcentages. Demandez un devis détaillé, une méthode de suivi et une organisation claire pour les interventions sur place.',
    sections: [
      { id: 'definition', title: 'Quel est le rôle d’une conciergerie Airbnb ?', paragraphs: ['La conciergerie sert d’interlocuteur pour les opérations qui lui sont confiées. Selon son offre, elle peut gérer la présentation du logement, suivre les demandes et coordonner les prestataires. Elle ne se confond pas avec Airbnb, qui est la plateforme de réservation.', 'Le propriétaire doit savoir quels sujets restent à sa charge et quelles décisions demandent son accord. Une mission de tarification seule, une aide à l’accueil et une gestion plus complète correspondent à des besoins et des coûts différents.'], links: [{ label: 'Comprendre le fonctionnement d’Airbnb au Maroc', href: '/fr/blog/airbnb-maroc-definition' }] },
      { id: 'services', title: 'Quels services comparer à Marrakech ?', paragraphs: ['Utilisez une liste commune lorsque vous demandez plusieurs devis. Pour chaque mission, demandez si elle est incluse, optionnelle ou réalisée par un prestataire facturé séparément. Les points suivants constituent une grille de comparaison, et non une promesse de services incluse dans toutes les offres.'], bullets: ['Création ou amélioration de l’annonce et coordination des photos.', 'Suivi des disponibilités et adaptation des prix.', 'Réponse aux messages et préparation des consignes d’arrivée.', 'Organisation de l’accueil et du départ selon le contrat.', 'Coordination du ménage, du linge et des consommables.', 'Signalement des problèmes et suivi des interventions autorisées.', 'Relevés de performance et transmission des justificatifs.'] },
      { id: 'logement', title: 'Adapter la gestion à un appartement, un riad ou une villa', paragraphs: ['Un appartement en copropriété demande de vérifier les accès, les règles de l’immeuble et les nuisances possibles. Pour un riad, documentez le parcours d’arrivée et les caractéristiques réelles du bâtiment. Pour une villa, intégrez le suivi des espaces extérieurs et des équipements spécifiques lorsqu’ils existent.', 'La visite initiale permet de transformer ces particularités en consignes concrètes. Demandez comment le prestataire organise les arrivées tardives, les dépannages et les périodes où plusieurs départs se suivent. Prévoir ces situations aide à juger la qualité du service proposé.'] },
      { id: 'tarifs', title: 'Combien coûte une conciergerie Airbnb à Marrakech ?', paragraphs: ['Le prix dépend du périmètre proposé et du mode de facturation. Pour comprendre un devis, demandez si les honoraires sont fixes, proportionnels aux recettes ou calculés par prestation. Vérifiez la base du pourcentage et le traitement des frais Airbnb, du ménage et des taxes.', 'Demandez également quels frais peuvent être engagés sans votre accord et lesquels nécessitent une validation. Comparez le coût total pour un même scénario de réservations plutôt que le pourcentage affiché seul.', 'Les honoraires de gestion sont distincts des frais Airbnb. COOHOSTY présente ses offres sur devis : le contenu et le prix à retenir sont ceux de la proposition et du contrat correspondant à votre logement.'], links: [{ label: 'Comprendre les commissions Airbnb au Maroc', href: '/fr/blog/commission-airbnb-maroc' }] },
      { id: 'formalites', title: 'Qui gère les formalités et les documents ?', paragraphs: ['Faites préciser si le contrat couvre des démarches d’accueil, la tenue des documents ou uniquement la coordination opérationnelle. La réglementation marocaine de l’hébergement touristique comporte des obligations spécifiques ; elles doivent être identifiées pour votre logement.', 'Demandez qui dispose des accès autorisés, comment les données des voyageurs sont protégées et comment vous récupérez les justificatifs. Pour la fiscalité, identifiez également le rôle de votre expert-comptable. Une mission de conciergerie ne doit pas être assimilée automatiquement à une prestation juridique ou comptable.'], sources: ['tourism'], links: [{ label: 'Lire le guide fiche de police Airbnb Maroc', href: '/fr/blog/fiche-de-police-airbnb-maroc' }, { label: 'Préparer votre dossier fiscal', href: '/fr/blog/fiscalite-taxes-airbnb-maroc' }] },
      { id: 'questions', title: 'Les questions à poser avant de confier votre logement', paragraphs: ['Une offre claire doit vous permettre de comprendre le fonctionnement quotidien et la fin de la collaboration. Demandez des réponses écrites aux points qui influencent votre décision.'], bullets: ['Qui intervient sur place et comment les urgences sont-elles traitées ?', 'Qui conserve le contrôle du compte Airbnb et reçoit les versements ?', 'Comment les prix, les dépenses et les disponibilités sont-ils validés ?', 'À quelle fréquence recevez-vous un relevé et les justificatifs ?', 'Quels services sont exclus ou facturés en supplément ?', 'Quel est le préavis et comment sont traitées les réservations en cours ?'] },
      { id: 'coohosty', title: 'Choisir l’accompagnement adapté avec COOHOSTY', paragraphs: ['Les offres AUDIT, OPTIMIZE et COHOST permettent d’examiner différents niveaux d’accompagnement. Consultez les détails pour comparer l’analyse de l’annonce, l’optimisation et les missions de gestion proposées.', 'Pour votre demande, indiquez le quartier, le type de logement, sa capacité et son état actuel : déjà publié, prêt à accueillir ou encore en préparation. Précisez votre disponibilité et les tâches que vous souhaitez déléguer. Ces éléments permettent de discuter d’un périmètre concret et d’un devis adapté.'], links: [{ label: 'Consulter l’offre AUDIT', href: '/fr/services/audit' }, { label: 'Consulter l’offre OPTIMIZE', href: '/fr/services/optimize' }, { label: 'Consulter l’offre COHOST', href: '/fr/services/cohost' }] },
    ],
    faq: [
      { question: 'Une conciergerie garantit-elle les revenus Airbnb ?', answer: 'Une projection ne garantit pas les réservations. Demandez les hypothèses de prix, d’occupation et de dépenses, puis comparez plusieurs scénarios.' },
      { question: 'La conciergerie est-elle obligatoirement locataire du logement ?', answer: 'Non. Elle peut intervenir pour le compte du propriétaire avec un contrat de gestion. Ce fonctionnement diffère de la sous-location.' },
      { question: 'Comment comparer deux conciergeries à Marrakech ?', answer: 'Comparez le même périmètre : tâches, disponibilité, frais, base de commission, autorisation des dépenses, suivi et conditions de sortie.' },
    ],
    related: ['commission-airbnb-maroc', 'airbnb-maroc-definition', 'sous-location-airbnb-maroc'],
  },
];

export function getBlogPost(slug: string) {
  return blogPosts.find(post => post.slug === slug);
}

export function blogReadingTime(post: BlogPost) {
  const text = [post.intro, post.takeaway, ...post.sections.flatMap(section => [section.title, ...section.paragraphs, ...(section.bullets ?? [])]), ...post.faq.flatMap(item => [item.question, item.answer])].join(' ');
  return Math.max(1, Math.ceil(text.split(/\s+/).length / 200));
}
