import type { BlogPost } from './blog';
import { conciergerieBlogPosts } from './blog-conciergerie';

export const additionalBlogPosts: BlogPost[] = [
  {
    slug: 'creer-annonce-airbnb-maroc',
    title: 'Comment créer une annonce Airbnb au Maroc : les étapes pour bien démarrer',
    seoTitle: 'Créer une annonce Airbnb au Maroc : guide propriétaire',
    description: 'Photos, description, couchages, calendrier et accueil : préparez une annonce Airbnb au Maroc claire et fidèle à votre logement, étape par étape.',
    category: 'Première annonce', published: '2026-10-07', modified: '2026-10-07',
    intro: 'Créer une annonce Airbnb au Maroc demande plus que quelques photos et un titre. Le voyageur doit comprendre ce qu’il réserve, le propriétaire doit savoir comment accueillir et le calendrier doit correspondre aux disponibilités réelles. Voici une méthode pour préparer une première annonce sans laisser les détails importants au hasard.',
    takeaway: 'Préparez le logement, vérifiez ses conditions d’exploitation et réunissez des informations exactes avant de publier. Une annonce convaincante repose sur une promesse que vous pourrez tenir à chaque séjour.',
    sections: [
      { id: 'avant-publication', title: 'Vérifier le projet avant de créer l’annonce', paragraphs: ['Commencez par les points qui conditionnent votre activité : votre droit de proposer le logement, les démarches applicables à sa situation, votre assurance et votre organisation d’accueil. La création d’une annonce sur une plateforme ne valide pas automatiquement ces éléments.', 'Si vous êtes locataire, consultez le guide sur la sous-location avant de vous engager. Si vous êtes propriétaire, préparez les formalités liées aux voyageurs et faites préciser votre situation fiscale. Ces vérifications évitent de découvrir une contrainte importante après la première réservation.'], links: [{label: 'Sous-location Airbnb au Maroc : les vérifications du bail', href:'/fr/blog/sous-location-airbnb-maroc'}, {label:'Fiche de police et accueil des voyageurs', href:'/fr/blog/fiche-de-police-airbnb-maroc'}] },
      { id:'photos', title:'Photographier ce que le voyageur utilisera réellement', paragraphs:['Construisez une série cohérente : pièce de vie, chambres, salle de bain, cuisine et espaces extérieurs accessibles. Photographiez aussi les éléments qui influencent le choix du voyageur, comme un bureau, une terrasse ou l’accès au logement. Une vue du quartier doit être clairement distinguée d’une vue depuis l’appartement.', 'Airbnb propose une visite photo organisée par pièces. Utilisez cette structure pour rendre les espaces faciles à comprendre. Choisissez une image de couverture représentative ; une terrasse commune ne doit pas laisser croire à une terrasse privée. Évitez les filtres qui changent les couleurs ou donnent une fausse impression de volume.'], sources:['photoTour'] },
      { id:'description', title:'Rédiger un titre et une description précis', paragraphs:['Votre titre peut annoncer un atout vérifiable : terrasse, deux chambres, stationnement ou proximité d’un lieu identifié. Privilégiez une information utile aux superlatifs. Dans la description, expliquez pour qui le logement convient, comment les pièces sont réparties et ce qui est inclus.', 'À Casablanca, Rabat ou Marrakech, la localisation demande du contexte : accès, environnement, bruit éventuel et distances réalistes. Mentionnez les escaliers, les restrictions d’accès et les travaux connus. La transparence permet au voyageur de choisir un logement adapté à son séjour.'], bullets:['Indiquez la capacité et la configuration exacte des couchages.', 'Décrivez uniquement les équipements disponibles et fonctionnels.', 'Précisez les espaces partagés, les règles du logement et les limites utiles.'] },
      { id:'calendrier', title:'Vérifier les disponibilités et les conditions du séjour', paragraphs:['Bloquez vos dates personnelles et les périodes nécessaires à une intervention avant d’ouvrir le calendrier. Prévoyez le temps de ménage entre deux séjours. Si votre logement apparaît sur plusieurs plateformes, mettez en place une organisation qui évite de vendre les mêmes dates deux fois.', 'Relisez l’ensemble des conditions visibles : heures d’arrivée et de départ, frais, politique d’annulation et règles du logement. Examinez le montant attendu après les frais de plateforme et vos charges, puis vérifiez que l’offre reste cohérente avec ce que vous fournissez.'], links:[{label:'Comprendre la commission Airbnb au Maroc',href:'/fr/blog/commission-airbnb-maroc'}] },
      { id:'publier', title:'Publier et préparer la première arrivée', paragraphs:['Airbnb permet de démarrer une nouvelle annonce depuis l’espace hôte. Suivez les étapes affichées dans votre compte, puis contrôlez l’aperçu public : photos, adresse, disponibilité et informations essentielles doivent être cohérentes. Les contrôles et les étapes proposés par la plateforme peuvent évoluer.'], sources:['createListing'] },
      { id:'organisation', title:'Transformer l’annonce en une expérience régulière', paragraphs:['Préparez un message d’arrivée, une procédure de remise des clés et un contact joignable. Testez le Wi-Fi, l’eau chaude et les appareils avant le premier séjour. Une annonce soignée crée des attentes ; l’accueil et l’entretien doivent ensuite les respecter.', 'Après les premiers séjours, rassemblez les questions récurrentes et améliorez les informations qui ont manqué. Corrigez une consigne imprécise, ajoutez la photo d’un accès difficile ou expliquez un équipement. COOHOSTY peut vous accompagner dans cette préparation et l’organisation de la gestion, selon le périmètre convenu.'] },
    ],
    faq:[{question:'Peut-on créer une annonce avant que le logement soit prêt ?',answer:'Vous pouvez préparer votre contenu à l’avance. Ouvrez uniquement les dates pour lesquelles le logement et votre organisation seront réellement prêts à accueillir.'},{question:'Faut-il un photographe professionnel ?',answer:'C’est utile si vos images ne rendent pas les espaces lisibles. La priorité reste une représentation fidèle du logement, une bonne lumière et des photos nettes de chaque espace.'},{question:'Créer une annonce suffit-il pour louer légalement au Maroc ?',answer:'Non. Les conditions d’exploitation et les démarches locales doivent être vérifiées indépendamment de la publication sur Airbnb.'}],
    related:['airbnb-maroc-definition','commission-airbnb-maroc','conciergerie-airbnb-marrakech'],
  },
  {
    slug:'conciergerie-airbnb-casablanca',
    title:'Conciergerie Airbnb à Casablanca : que déléguer et comment choisir ?',
    seoTitle:'Conciergerie Airbnb Casablanca : guide de gestion',
    description:'Accueil, ménage, annonce et suivi du logement : comparez les missions d’une conciergerie Airbnb à Casablanca et choisissez un périmètre clair.',
    category:'Gestion à Casablanca', published:'2026-10-07',modified:'2026-10-07',
    intro:'Vous possédez un appartement à Casablanca et souhaitez déléguer sa gestion sur Airbnb ? Le mot conciergerie peut recouvrir des prestations très différentes. L’enjeu est de définir qui fait quoi, avec quels moyens, et comment vous suivez le fonctionnement du logement. Ce guide vous aide à comparer les offres sur des critères concrets.',
    takeaway:'Comparez le contenu de la prestation avant le pourcentage annoncé. Un accord clair doit couvrir l’accueil, le ménage, les dépenses, les accès aux comptes et le suivi des résultats.',
    sections:[
      {id:'missions',title:'Quelles missions peut couvrir une conciergerie à Casablanca ?',paragraphs:['Une mission complète peut inclure la préparation de l’annonce, le suivi du calendrier, les échanges avec les voyageurs, l’accueil et la coordination du ménage. Certains prestataires interviennent uniquement sur place ; d’autres assurent aussi la gestion commerciale. Demandez la liste des prestations incluses plutôt que de supposer que tout est couvert.', 'Définissez également les tâches occasionnelles : contrôle d’un appareil, achat de linge, passage après un incident ou coordination d’un artisan. Ces interventions n’ont pas le même coût ni le même fonctionnement qu’un ménage de rotation. Un interlocuteur identifiable et une procédure de validation facilitent le suivi.'],bullets:['Gestion de l’annonce et des messages.', 'Arrivées, départs et coordination du ménage.', 'Contrôles du logement et suivi des incidents.', 'Compte rendu des réservations et des dépenses.']},
      {id:'quartier',title:'Adapter la gestion au logement et à son environnement',paragraphs:['L’organisation d’un appartement à Casablanca dépend de ses accès et de son usage. Un étage sans ascenseur, un stationnement partagé ou un gardien imposent des consignes particulières. Testez le parcours d’arrivée avec une personne qui ne connaît pas l’immeuble : elle identifiera souvent les informations manquantes.', 'Décrivez votre quartier avec précision sans promettre des temps de trajet irréalistes. Pour un séjour professionnel, un espace de travail et un accès Internet fiable peuvent être des critères utiles ; pour un séjour familial, la répartition des couchages et l’accès aux services du quartier peuvent compter davantage. Vérifiez ces besoins avec les demandes que votre logement reçoit réellement.']},
      {id:'tarifs',title:'Comprendre les honoraires et les frais supplémentaires',paragraphs:['Une commission de gestion peut être calculée sur des bases différentes. Faites préciser si elle s’applique au montant des nuitées, au total de réservation ou à une autre assiette, et comment sont traités les frais de ménage. Demandez un exemple de décompte écrit pour un séjour fictif.', 'Les honoraires de conciergerie et les frais Airbnb constituent des postes distincts. Ajoutez les consommables, le linge, les déplacements exceptionnels et les petites interventions à votre comparaison. Une prestation moins chère peut demander davantage de travail au propriétaire si plusieurs missions restent à sa charge.'],links:[{label:'Commission Airbnb au Maroc : comprendre les frais de plateforme',href:'/fr/blog/commission-airbnb-maroc'}]},
      {id:'contrat',title:'Les points à clarifier avant de signer',paragraphs:['Précisez qui détient les accès aux annonces, qui valide les dépenses et qui reçoit les versements. Définissez les dates d’usage personnel, les délais de résiliation et la remise des clés en fin de mission. Demandez aussi comment seront transmis les documents et les informations nécessaires pour reprendre la gestion.', 'Les formalités d’accueil et les obligations du propriétaire doivent être attribuées explicitement. La délégation d’une tâche opérationnelle ne dispense pas de vérifier la situation de votre logement. Appuyez-vous sur les guides dédiés pour préparer ces échanges, puis faites confirmer les obligations propres à votre activité.'],links:[{label:'Fiscalité et taxes Airbnb au Maroc',href:'/fr/blog/fiscalite-taxes-airbnb-maroc'},{label:'Organiser les formalités d’accueil',href:'/fr/blog/fiche-de-police-airbnb-maroc'}]},
      {id:'suivi',title:'Suivre la gestion avec des indicateurs compréhensibles',paragraphs:['Un suivi utile présente les nuits disponibles, les nuits réservées, les recettes et les frais sur la même période. Distinguez les dates bloquées par le propriétaire des dates proposées aux voyageurs. Sans cette distinction, un taux d’occupation peut donner une impression trompeuse.', 'Demandez un relevé des incidents, des travaux recommandés et des actions à prévoir. Il doit vous aider à décider : remplacer un équipement, modifier une consigne ou revoir la disponibilité du logement. Les résultats varient avec le bien, son emplacement et la période ; aucune commission ne garantit à elle seule un revenu.']},
      {id:'coohosty',title:'Préparer un échange avec COOHOSTY',paragraphs:['Pour définir une mission adaptée à Casablanca, réunissez l’adresse ou le quartier du bien, sa capacité, quelques photos et vos contraintes de disponibilité. Si une annonce existe, partagez son lien et les difficultés rencontrées : accueil, entretien, messages ou suivi des réservations.', 'Nous pouvons ensuite examiner vos besoins et préciser les services à prévoir. L’objectif est une gestion compréhensible, avec une responsabilité claire pour chaque étape et des informations que vous pouvez suivre dans le temps.'],links:[{label:'Présenter mon logement à COOHOSTY',href:'/fr#estimate'}]},
    ],
    faq:[{question:'Une conciergerie gère-t-elle uniquement le ménage ?',answer:'Cela dépend de la prestation. Certaines proposent une intervention locale ; d’autres assurent aussi l’annonce, le calendrier, les messages et l’accueil. Faites préciser chaque mission.'},{question:'Comment comparer deux devis de conciergerie à Casablanca ?',answer:'Comparez l’assiette des honoraires, les missions incluses, les frais supplémentaires, les modalités de suivi et les conditions de fin de contrat.'},{question:'Puis-je garder des dates pour mon usage personnel ?',answer:'Faites prévoir vos dates et la procédure de blocage dans l’organisation convenue. Le calendrier doit être mis à jour avant qu’une réservation soit acceptée.'}],
    related:['conciergerie-airbnb-marrakech','commission-airbnb-maroc','creer-annonce-airbnb-maroc'],
  },
  ...conciergerieBlogPosts,
];
