import type { Locale } from '@/config/site';
import { type CityMarket, cityName, getCohostingCity } from '@/config/cohosting-cities';
import { marrakechMessages } from './marrakech-messages';

export const cohostingCopy = {
  fr: { eyebrow: 'COHOSTING · GESTION COMPLÈTE', title: 'Votre bien.', accent: 'Notre attention.', intro: 'Vous nous confiez les clés. Nous prenons soin de votre annonce, de vos voyageurs et de votre logement.', discover: 'Découvrir les services', start: 'Parlons de votre bien', commissionEyebrow: 'UNE COMMISSION. UN ACCOMPAGNEMENT COMPLET.', commissionTitle: 'Le service est complet.', commissionAccent: 'La commission, simplement 20 %.', rateLabel: 'de commission par réservation', rateNote: 'Le même taux à Marrakech, Casablanca et Tanger.', example: 'Votre commission, en clair', base: 'Montant retenu pour le calcul', reservation: 'Une réservation', month: 'Le total du mois', management: 'Commission COOHOSTY', balance: 'Solde avant autres frais', explanation: '20 % sur chaque réservation ou 20 % sur leur total : à base identique, le résultat est le même.', terms: 'Exemple indicatif. Le devis précise la base de calcul, le traitement des frais de plateforme, du ménage et des taxes, ainsi que les dépenses complémentaires.', services: 'Tout ce qui fait un séjour réussi.', servicesIntro: 'Les mêmes services COHOST dans les trois villes. Une organisation adaptée à votre logement.', localTitle: 'Le même soin.', localAccent: 'Une attention locale.', areaLabel: 'Votre quartier, votre logement', localNote: 'Le périmètre et les modalités d’intervention sont définis avec vous avant le démarrage.', citiesTitle: 'Trois villes. La même exigence.', cityLink: 'Découvrir le cohosting', faqTitle: 'Les réponses, simplement.', faqRate: 'Comment se calcule la commission de 20 % ?', faqServices: 'Quels services sont compris ?', faqExpenses: 'Qu’en est-il du ménage et des autres frais ?', expenses: 'La gestion des prestations fait partie de notre accompagnement. Le devis distingue la commission, les frais de plateforme, le ménage, les taxes et les dépenses d’entretien éventuelles. Leur traitement est précisé avant tout engagement.', faqStart: 'Comment confier mon logement ?', startAnswer: 'Présentez votre logement dans le formulaire. Nous étudions ses caractéristiques et son emplacement, puis vous proposons un périmètre de gestion et un devis adapté.', formTitle: 'Votre prochain séjour commence ici.', photo: 'Illustration de logement', home: 'Accueil', breadcrumb: 'Cohosting', guide: 'Le guide pour propriétaires', serviceScope: 'Les modalités et le périmètre des prestations sont précisés dans votre devis.' },
  en: { eyebrow: 'COHOSTING · COMPLETE MANAGEMENT', title: 'Your property.', accent: 'Our attention.', intro: 'You hand us the keys. We care for your listing, your guests and your home.', discover: 'Explore the services', start: 'Let’s discuss your property', commissionEyebrow: 'ONE COMMISSION. COMPLETE SUPPORT.', commissionTitle: 'A complete service.', commissionAccent: 'Simply 20% commission.', rateLabel: 'commission per booking', rateNote: 'The same rate in Marrakech, Casablanca and Tangier.', example: 'Your commission, clearly', base: 'Amount used for calculation', reservation: 'One booking', month: 'Monthly total', management: 'COOHOSTY commission', balance: 'Balance before other costs', explanation: '20% on each booking or 20% on their total: with the same calculation basis, the result is identical.', terms: 'Illustrative calculation. Your quote specifies the calculation basis, platform fees, cleaning, taxes and additional expenses.', services: 'Everything behind a great stay.', servicesIntro: 'The same COHOST services in all three cities, organised around your property.', localTitle: 'The same care.', localAccent: 'Local attention.', areaLabel: 'Your neighbourhood, your property', localNote: 'Service coverage and arrangements are agreed with you before management begins.', citiesTitle: 'Three cities. The same care.', cityLink: 'Explore cohosting', faqTitle: 'Clear answers.', faqRate: 'How is the 20% commission calculated?', faqServices: 'Which services are included?', faqExpenses: 'What about cleaning and other costs?', expenses: 'Coordinating services is part of our support. Your quote distinguishes management commission, platform fees, cleaning, taxes and any maintenance costs. Their treatment is specified before you commit.', faqStart: 'How do I get started?', startAnswer: 'Describe your property in the form. We review its features and location, then propose a suitable management scope and quote.', formTitle: 'Your next stay starts here.', photo: 'Property illustration', home: 'Home', breadcrumb: 'Cohosting', guide: 'The owner’s guide', serviceScope: 'Service terms and scope are specified in your quote.' },
  ar: { eyebrow: 'COHOSTING · إدارة متكاملة', title: 'عقارك.', accent: 'اهتمامنا.', intro: 'تسلّمنا المفاتيح، ونهتم بإعلانك وضيوفك وعقارك.', discover: 'اكتشف الخدمات', start: 'لنتحدث عن عقارك', commissionEyebrow: 'عمولة واحدة. عناية متكاملة.', commissionTitle: 'الخدمة متكاملة.', commissionAccent: 'والعمولة ببساطة 20%.', rateLabel: 'عمولة عن كل حجز', rateNote: 'النسبة نفسها في مراكش والدار البيضاء وطنجة.', example: 'عمولتك بوضوح', base: 'المبلغ المعتمد للحساب', reservation: 'حجز واحد', month: 'مجموع الشهر', management: 'عمولة COOHOSTY', balance: 'الرصيد قبل المصاريف الأخرى', explanation: '20% من كل حجز أو 20% من مجموع الحجوزات: النتيجة نفسها عند اعتماد أساس الحساب نفسه.', terms: 'حساب توضيحي. يحدد عرض السعر أساس الحساب ورسوم المنصة والتنظيف والضرائب والمصاريف الإضافية.', services: 'كل ما يجعل الإقامة ناجحة.', servicesIntro: 'خدمات COHOST نفسها في المدن الثلاث، بتنظيم يناسب عقارك.', localTitle: 'العناية نفسها.', localAccent: 'باهتمام محلي.', areaLabel: 'حيّك وعقارك', localNote: 'يتم الاتفاق معك على نطاق الخدمة وكيفية التدخل قبل بدء الإدارة.', citiesTitle: 'ثلاث مدن. العناية نفسها.', cityLink: 'اكتشف إدارة العقار', faqTitle: 'إجابات واضحة.', faqRate: 'كيف تُحسب عمولة 20%؟', faqServices: 'ما الخدمات المشمولة؟', faqExpenses: 'ماذا عن التنظيف والمصاريف الأخرى؟', expenses: 'تنسيق الخدمات جزء من مرافقتنا. يوضح عرض السعر عمولة الإدارة ورسوم المنصة والتنظيف والضرائب ومصاريف الصيانة المحتملة قبل أي التزام.', faqStart: 'كيف أبدأ؟', startAnswer: 'قدّم تفاصيل عقارك في الاستمارة. ندرس خصائصه وموقعه، ثم نقترح نطاق إدارة وعرض سعر مناسبين.', formTitle: 'إقامتك القادمة تبدأ هنا.', photo: 'صورة توضيحية للعقار', home: 'الرئيسية', breadcrumb: 'إدارة العقارات', guide: 'دليل المالك', serviceScope: 'تُحدد شروط الخدمات ونطاقها في عرض السعر.' },
} satisfies Record<Locale, Record<string, string>>;

const cityDescriptions = {
  marrakech: { fr: 'Appartements à Guéliz ou Hivernage, riads dans la Médina, villas dans la Palmeraie : les accès, les arrivées et l’entretien se préparent selon votre bien.', en: 'Apartments in Gueliz or Hivernage, riads in the Medina, villas in the Palmeraie: access, arrivals and care are organised around your home.', ar: 'شقق جليز والحي الشتوي، ورياض المدينة القديمة وفلل النخيل: نهيئ الوصول والاستقبال والعناية وفق احتياجات عقارك.' },
  casablanca: { fr: 'Pour un appartement à Maârif, Gauthier ou Racine, ou un logement à Aïn Diab, nous organisons les accès, le confort et le suivi entre les séjours. Les règles de la résidence et les besoins du logement guident la préparation.', en: 'For an apartment in Maarif, Gauthier or Racine, or a home in Ain Diab, we organise access, comfort and care between stays. Residence rules and the needs of the property guide preparations.', ar: 'لشقة في المعاريف أو غوتييه أو راسين، أو مسكن في عين الذياب، ننظم الوصول والراحة والمتابعة بين الإقامات وفق قواعد الإقامة واحتياجات العقار.' },
  tanger: { fr: 'À Malabata, Iberia, Marshan ou dans le centre-ville, votre appartement ou maison demande une organisation attentive : accès, accueil et entretien des espaces. Nous préparons la gestion selon les caractéristiques de votre logement.', en: 'In Malabata, Iberia, Marshan or the city centre, your apartment or home needs thoughtful organisation: access, welcoming guests and caring for spaces. Management is planned around your property.', ar: 'في مالباطا أو إيبيريا أو مرشان أو وسط المدينة، يحتاج عقارك إلى تنظيم دقيق للوصول والاستقبال والعناية بالمساحات. نخطط للإدارة حسب خصائص مسكنك.' },
};
export function cityDescription(market: CityMarket, locale: Locale) { return cityDescriptions[market][locale]; }
export function citySeoTitle(market: CityMarket, locale: Locale) {
  const name = cityName(market, locale);
  return locale === 'fr' ? `Cohosting ${name} · Conciergerie Airbnb à 20 % | COOHOSTY` : locale === 'en' ? `${name} Airbnb Cohosting · 20% Management | COOHOSTY` : `إدارة Airbnb في ${name} بعمولة 20% | COOHOSTY`;
}
export function citySeoDescription(market: CityMarket, locale: Locale) {
  const name = cityName(market, locale);
  return locale === 'fr' ? `Cohosting à ${name} : gestion des annonces, voyageurs et logement. Tous les services COHOST avec une commission fixe de 20 % par réservation. Découvrez notre offre.` : locale === 'en' ? `Cohosting in ${name}: listing, guest and property management. All COHOST services with a fixed 20% commission per booking. Explore our offer.` : `إدارة عقارك في ${name}: الإعلان والضيوف والعناية بالمسكن. جميع خدمات COHOST بعمولة ثابتة 20% عن كل حجز.`;
}
export function getCityMessages(market: CityMarket, locale: Locale) {
  const name = cityName(market, locale);
  const originalName = locale === 'ar' ? 'مراكش' : 'Marrakech';
  const base = JSON.parse(JSON.stringify(marrakechMessages[locale]).replaceAll(originalName, name)) as typeof marrakechMessages[typeof locale];
  // Local content must describe this city, not inherit Marrakech neighbourhoods.
  base.faq.items.onSite.answer = cityDescription(market, locale);
  base.estimate.placeholders.city = getCohostingCity(market).name;
  base.faq.items.price.answer = `${cohostingCopy[locale].explanation} ${cohostingCopy[locale].terms}`;
  return base;
}
