import type { Locale } from '@/config/site';

export const marrakechServicePath = '/services/conciergerie-marrakech';
export const marrakechServiceModified = '2026-10-09';
export const marrakechCommissionRate = 0.2;
export const marrakechServiceContent = {
  fr: { title: 'Conciergerie Airbnb à Marrakech', seoTitle: 'Conciergerie Marrakech : gestion Airbnb à 20 % | COOHOSTY', description: 'Votre conciergerie Airbnb à Marrakech : tous les services COOHOSTY, gestion à 20 % des réservations et accompagnement à Guéliz, Hivernage, Médina et Palmeraie.', linkLabel: 'Conciergerie Airbnb à Marrakech', commission: '20 % du montant des réservations', commissionTitle: 'Votre gestion à Marrakech. Une commission de 20 %.', commissionBody: 'Pour la gestion COHOST à Marrakech, notre commission est de 20 % du montant des réservations. Les modalités de calcul, les prestations et les dépenses complémentaires sont précisées dans votre devis. AUDIT et OPTIMIZE restent disponibles selon le niveau d’accompagnement choisi.', servicesTitle: 'Tous les services pour votre logement à Marrakech', mapTitle: 'Marrakech. Quartier par quartier.', mapIntro: 'Guéliz, Hivernage, Médina ou Palmeraie : choisissez votre quartier pour découvrir les besoins d’un appartement, d’un riad ou d’une villa en location courte durée.', mapLabel: 'Carte des quartiers de Marrakech', mapHint: 'Sélectionnez un quartier. Les repères sont indicatifs.', readGuide: 'Lire le guide du quartier', illustration: 'Illustration de logement', journalTitle: 'Les quartiers de Marrakech, côté propriétaire', journalAll: 'Tous les guides', home: 'Accueil', services: 'Services', scope: 'À Marrakech uniquement · modalités précisées au devis' },
  en: { title: 'Airbnb property management in Marrakech', seoTitle: 'Marrakech Airbnb Management at 20% | COOHOSTY', description: 'All COOHOSTY services for your Marrakech property, with a 20% booking commission. Explore Gueliz, Hivernage, the Medina and the Palmeraie.', linkLabel: 'Airbnb management in Marrakech', commission: '20% of the booking amount', commissionTitle: 'Your Marrakech management. A 20% commission.', commissionBody: 'Our commission for COHOST management in Marrakech is 20% of the booking amount. Calculation terms, services and additional expenses are specified in your quote. AUDIT and OPTIMIZE remain available for the level of support you choose.', servicesTitle: 'All services for your Marrakech property', mapTitle: 'Marrakech. Neighbourhood by neighbourhood.', mapIntro: 'Gueliz, Hivernage, the Medina or the Palmeraie: select an area to explore the needs of an apartment, riad or villa offered for short stays.', mapLabel: 'Map of Marrakech neighbourhoods', mapHint: 'Select an area. Location markers are indicative.', readGuide: 'Read the neighbourhood guide (French)', illustration: 'Property illustration', journalTitle: 'Marrakech neighbourhoods for property owners', journalAll: 'All guides (French)', home: 'Home', services: 'Services', scope: 'Marrakech only · terms specified in your quote' },
  ar: { title: 'إدارة سكن Airbnb في مراكش', seoTitle: 'إدارة سكن Airbnb في مراكش بعمولة 20% | COOHOSTY', description: 'جميع خدمات COOHOSTY لعقارك في مراكش بعمولة 20% من مبلغ الحجوزات. اكتشف جليز والحي الشتوي والمدينة القديمة والنخيل.', linkLabel: 'إدارة سكن Airbnb في مراكش', commission: '20% من مبلغ الحجوزات', commissionTitle: 'إدارة عقارك في مراكش بعمولة 20%.', commissionBody: 'تبلغ عمولتنا لخدمة COHOST في مراكش 20% من مبلغ الحجوزات. يوضح عرض السعر طريقة الحساب والخدمات والمصاريف الإضافية. ويمكنك اختيار AUDIT أو OPTIMIZE حسب مستوى المساعدة الذي تحتاجه.', servicesTitle: 'جميع الخدمات لعقارك في مراكش', mapTitle: 'مراكش. حيّاً بحي.', mapIntro: 'جليز أو الحي الشتوي أو المدينة القديمة أو النخيل: اختر الحي لاكتشاف احتياجات شقة أو رياض أو فيلا للإيجار القصير.', mapLabel: 'خريطة أحياء مراكش', mapHint: 'اختر الحي. مواقع العلامات تقريبية.', readGuide: 'قراءة دليل الحي بالفرنسية', illustration: 'صورة توضيحية للسكن', journalTitle: 'أحياء مراكش من منظور المالك', journalAll: 'جميع الأدلة بالفرنسية', home: 'الرئيسية', services: 'الخدمات', scope: 'في مراكش فقط · التفاصيل ضمن عرض السعر' },
} satisfies Record<Locale, Record<string, string>>;

export const marrakechNeighborhoods = [
  { id: 'gueliz', lat: 31.6345, lon: -8.0117, slug: 'location-courte-duree-gueliz-marrakech', image: '/images/hero-airbnb.webp', source: 'https://visitmarrakech.com/listing/gueliz/', names: { fr: 'Guéliz', en: 'Gueliz', ar: 'جليز' }, details: { fr: 'Appartements en ville : accès, confort et organisation des séjours.', en: 'City apartments: access, comfort and guest stays.', ar: 'شقق المدينة: سهولة الوصول والراحة وتنظيم الإقامات.' } },
  { id: 'hivernage', lat: 31.6219, lon: -8.0073, slug: 'location-courte-duree-hivernage-marrakech', image: '/images/hero-interior-3.webp', source: 'https://visitmarrakech.com/en/listing/lhivernage/', names: { fr: 'Hivernage', en: 'Hivernage', ar: 'الحي الشتوي' }, details: { fr: 'Appartements et résidences : qualité d’accueil et suivi du logement.', en: 'Apartments and residences: welcoming guests and caring for the home.', ar: 'شقق وإقامات: جودة الاستقبال ومتابعة العقار.' } },
  { id: 'medina', lat: 31.6292, lon: -7.9846, slug: 'location-courte-duree-medina-marrakech', image: '/images/hero-interior-warm.webp', source: 'https://visitmarrakech.com/en/listing/la-medina-de-marrakech/', names: { fr: 'Médina', en: 'Medina', ar: 'المدينة القديمة' }, details: { fr: 'Riads et logements de caractère : préparer les accès et les arrivées.', en: 'Riads and distinctive homes: plan access and arrivals.', ar: 'رياض ومساكن مميزة: تجهيز الوصول واستقبال الضيوف.' } },
  { id: 'palmeraie', lat: 31.686, lon: -7.967, slug: 'location-courte-duree-palmeraie-marrakech', image: '/images/hero-interior-4.webp', source: 'https://mice.visitmarrakech.com/listing/palmeraie-de-marrakech/', names: { fr: 'Palmeraie', en: 'Palmeraie', ar: 'النخيل' }, details: { fr: 'Villas et espaces extérieurs : entretien, déplacements et coordination.', en: 'Villas and outdoor spaces: maintenance, transport and coordination.', ar: 'فلل ومساحات خارجية: العناية والتنقل وتنسيق الخدمات.' } },
] as const;
export const marrakechNeighborhoodSlugs: readonly string[] = marrakechNeighborhoods.map(area => area.slug);
